import json
import platform
import sys
from datetime import datetime, timezone
from io import BytesIO
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape

from docx import Document
from fastapi import HTTPException
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.database import get_connection, init_db
from app.models.final_report_models import (
    FinalProjectReportRequest,
    FinalProjectReportResponse,
    FinalProjectReportSection,
    FinalProjectReportSummary,
)
from app.models.project_workspace_models import ProjectAttachRequest
from app.services.admet_trained_model_service import get_active_trained_model_info
from app.services.local_admet_model import validate_local_admet_model
from app.services.model_registry import model_status_response
from app.services.project_workspace_service import attach_project_item, project_dashboard
from app.services.version import app_version

REPORT_DIR = Path(__file__).resolve().parents[2] / "final_project_reports"
SCIENTIFIC_NOTICE = "Computational decision-support report only. Experimental and clinical interpretation requires qualified scientific review."
FINAL_LIMITATIONS = [
    "This report summarizes stored DrugScreen360 records only; missing data is not inferred.",
    "No experimental result is invented, simulated, or generated by DrugScreen360.",
    "Computational outputs do not prove safety, efficacy, clinical success, regulatory approval, or market readiness.",
    "Applicability-domain, uncertainty, explainability, and model metrics are dataset-dependent.",
    "Qualified scientific review and experimental validation are required before any research decision.",
]


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _timestamp(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%d_%H-%M-%S")


def _safe(value: Any) -> str:
    if value in (None, "", [], {}):
        return "not available"
    if isinstance(value, (dict, list)):
        return json.dumps(value, default=str)[:900]
    return str(value)


def _text(value: Any, max_len: int = 240) -> str:
    if value in (None, "", [], {}):
        return "not available"
    if isinstance(value, bool):
        return "Pass" if value else "Fail"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        value = "; ".join(str(item) for item in value if item not in (None, "", [], {}))
    elif isinstance(value, dict):
        parts = []
        for key, item in value.items():
            if item not in (None, "", [], {}):
                parts.append(f"{str(key).replace('_', ' ')}: {item}")
        value = "; ".join(parts)
    value = str(value).replace("\n", " ").strip()
    return value[:max_len] + ("..." if len(value) > max_len else "")


def _first_available(*values: Any) -> Any:
    for value in values:
        if value not in (None, "", [], {}, "not available", "not evaluated"):
            return value
    return None


def _rows(table: str, project_id: int | None = None, limit: int = 100) -> list[dict[str, Any]]:
    init_db()
    with get_connection() as connection:
        if project_id and table in {
            "experimental_validation_plans",
            "experimental_result_batches",
            "prediction_feedback_summaries",
            "admet_lead_prioritization_runs",
        }:
            rows = connection.execute(
                f"SELECT * FROM {table} WHERE project_id = ? ORDER BY datetime(created_at) DESC, id DESC LIMIT ?",
                (project_id, limit),
            ).fetchall()
        else:
            rows = connection.execute(
                f"SELECT * FROM {table} ORDER BY datetime(created_at) DESC, id DESC LIMIT ?",
                (limit,),
            ).fetchall()
    return [dict(row) for row in rows]


def _json_loads(value: Any, default: Any) -> Any:
    if not value:
        return default
    try:
        return json.loads(value)
    except Exception:
        return default


def _section(section_id: str, title: str, requested: bool, records: list[dict[str, Any]], summary: dict[str, Any], warnings: list[str] | None = None) -> FinalProjectReportSection:
    section_warnings = list(warnings or [])
    included = bool(requested and (records or summary))
    if requested and not included:
        section_warnings.append(f"{title} was requested but no stored records were available.")
    return FinalProjectReportSection(
        section_id=section_id,
        title=title,
        included=included,
        summary=summary if requested else {"status": "not requested"},
        records=records if requested else [],
        warnings=section_warnings,
    )


def _screening_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    records = _rows("screening_history", limit=50)
    summary = {
        "screening_run_count": len(records),
        "recent_compounds": [row.get("compound_name") or row.get("input_query") for row in records[:8]],
        "decisions": {},
    }
    for row in records:
        decision = row.get("decision") or "not available"
        summary["decisions"][decision] = summary["decisions"].get(decision, 0) + 1
    clean_records = [
        {
            "id": r.get("id"),
            "input_query": r.get("input_query"),
            "input_type": r.get("input_type"),
            "compound_name": r.get("compound_name"),
            "pubchem_cid": r.get("pubchem_cid"),
            "canonical_smiles": r.get("canonical_smiles"),
            "decision": r.get("decision"),
            "created_at": r.get("created_at"),
        }
        for r in records
    ]
    return _section("screening", "Molecule Screening Summary", payload.include_screening, clean_records, summary)


def _training_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    datasets = _rows("admet_datasets", limit=50)
    runs = _rows("admet_training_runs", limit=50)
    summary = {
        "dataset_count": len(datasets),
        "training_run_count": len(runs),
        "latest_training_runs": [
            {
                "id": row.get("id"),
                "task_type": row.get("task_type"),
                "model_type": row.get("model_type"),
                "status": row.get("status"),
                "metrics": _json_loads(row.get("metric_summary_json"), {}),
            }
            for row in runs[:5]
        ],
    }
    clean_datasets = [
        {
            "id": r.get("id"),
            "name": r.get("name"),
            "task_name": r.get("task_name"),
            "label_column": r.get("label_column"),
            "original_filename": r.get("original_filename"),
            "record_count": r.get("record_count"),
            "valid_count": r.get("valid_count"),
            "invalid_count": r.get("invalid_count"),
            "duplicate_count": r.get("duplicate_count"),
            "status": r.get("status"),
            "created_at": r.get("created_at"),
        }
        for r in datasets
    ]
    clean_runs = [
        {
            "id": r.get("id"),
            "dataset_id": r.get("dataset_id"),
            "task_name": r.get("task_name"),
            "task_type": r.get("task_type"),
            "model_name": r.get("model_name"),
            "model_type": r.get("model_type"),
            "status": r.get("status"),
            "train_count": r.get("train_count"),
            "test_count": r.get("test_count"),
            "created_at": r.get("created_at"),
        }
        for r in runs
    ]
    return _section("model_training", "ADMET Dataset & Training Summary", payload.include_model_training, clean_datasets + clean_runs, summary)


def _prediction_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    model_status = model_status_response()
    active = get_active_trained_model_info()
    logs = _rows("model_prediction_logs", limit=50)
    summary = {
        "active_trained_model": active,
        "available_models": [item.model_dump() for item in model_status["available_models"]],
        "unavailable_models": [item.model_dump() for item in model_status["unavailable_models"]],
        "prediction_log_count": len(logs),
    }
    clean_logs = [
        {
            "id": r.get("id"),
            "smiles": r.get("smiles"),
            "model_id": r.get("model_id"),
            "task_name": r.get("task_name"),
            "prediction_label": r.get("prediction_label"),
            "prediction_score": r.get("prediction_score"),
            "confidence": r.get("confidence"),
            "status": r.get("status"),
            "created_at": r.get("created_at"),
        }
        for r in logs
    ]
    return _section("admet_prediction", "Trained Model Prediction Summary", payload.include_admet_prediction, clean_logs, summary)


def _external_validation_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    records = _rows("admet_external_validation_runs", limit=50)
    summary = {
        "external_validation_run_count": len(records),
        "latest_status": records[0].get("status") if records else "not available",
        "latest_metrics": _json_loads(records[0].get("metric_summary_json"), {}) if records else {},
    }
    clean_records = [
        {
            "id": r.get("id"),
            "model_id": r.get("model_id"),
            "training_run_id": r.get("training_run_id"),
            "external_dataset_id": r.get("external_dataset_id"),
            "task_name": r.get("task_name"),
            "task_type": r.get("task_type"),
            "status": r.get("status"),
            "valid_count": r.get("valid_count"),
            "invalid_count": r.get("invalid_count"),
            "created_at": r.get("created_at"),
        }
        for r in records
    ]
    return _section("external_validation", "External Validation & Calibration", payload.include_external_validation, clean_records, summary)


def _domain_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    records = _rows("admet_domain_evaluations", limit=100)
    counts: dict[str, int] = {}
    uncertainty: dict[str, int] = {}
    for row in records:
        counts[row.get("domain_status") or "unknown"] = counts.get(row.get("domain_status") or "unknown", 0) + 1
        uncertainty[row.get("uncertainty_level") or "unknown"] = uncertainty.get(row.get("uncertainty_level") or "unknown", 0) + 1
    summary = {"domain_status_counts": counts, "uncertainty_distribution": uncertainty, "evaluation_count": len(records)}
    clean_records = [
        {
            "id": r.get("id"),
            "model_id": r.get("model_id"),
            "training_run_id": r.get("training_run_id"),
            "smiles": r.get("smiles"),
            "canonical_smiles": r.get("canonical_smiles"),
            "domain_status": r.get("domain_status"),
            "uncertainty_level": r.get("uncertainty_level"),
            "created_at": r.get("created_at"),
        }
        for r in records
    ]
    return _section("applicability_domain", "Applicability Domain & Uncertainty", payload.include_applicability_domain, clean_records, summary)


def _explainability_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    records = _rows("admet_prediction_explanations", limit=50)
    evidence: dict[str, int] = {}
    for row in records:
        evidence[row.get("evidence_strength") or "unknown"] = evidence.get(row.get("evidence_strength") or "unknown", 0) + 1
    summary = {
        "explanation_count": len(records),
        "evidence_strength_distribution": evidence,
        "causality_notice": "Feature importance and coefficients are model diagnostics, not biological causality.",
    }
    clean_records = [
        {
            "id": r.get("id"),
            "model_id": r.get("model_id"),
            "training_run_id": r.get("training_run_id"),
            "smiles": r.get("smiles"),
            "canonical_smiles": r.get("canonical_smiles"),
            "evidence_strength": r.get("evidence_strength"),
            "domain_status": r.get("domain_status"),
            "uncertainty_level": r.get("uncertainty_level"),
            "created_at": r.get("created_at"),
        }
        for r in records
    ]
    return _section("explainability", "Prediction Explainability", payload.include_explainability, clean_records, summary)


def _lead_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    records = _rows("admet_lead_prioritization_runs", payload.project_id, limit=50)
    top_candidates = []
    for row in records[:5]:
        summary_json = _json_loads(row.get("summary_json"), {})
        top_candidates.extend((summary_json.get("ranked_candidates") or [])[:3])
    summary = {
        "lead_run_count": len(records),
        "top_candidates": top_candidates[:10],
        "priority_label_counts": {},
    }
    for candidate in top_candidates:
        label = candidate.get("priority_label") or "not available"
        summary["priority_label_counts"][label] = summary["priority_label_counts"].get(label, 0) + 1
    clean_records = [
        {
            "id": r.get("id"),
            "project_id": r.get("project_id"),
            "source_type": r.get("source_type"),
            "candidate_count": r.get("candidate_count"),
            "ranked_count": r.get("ranked_count"),
            "excluded_count": r.get("excluded_count"),
            "scoring_profile": r.get("scoring_profile"),
            "created_at": r.get("created_at"),
        }
        for r in records
    ]
    return _section("lead_prioritization", "Lead Prioritization", payload.include_lead_prioritization, clean_records, summary)


def _validation_planner_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    records = _rows("experimental_validation_plans", payload.project_id, limit=50)
    essential = recommended = optional = 0
    for row in records:
        summary_json = _json_loads(row.get("summary_json"), {})
        for candidate in summary_json.get("candidate_plans", []):
            for assay in candidate.get("recommended_assays", []):
                if assay.get("recommendation_priority") == "essential":
                    essential += 1
                elif assay.get("recommendation_priority") == "recommended":
                    recommended += 1
                elif assay.get("recommendation_priority") == "optional":
                    optional += 1
    summary = {
        "validation_plan_count": len(records),
        "essential_assay_count": essential,
        "recommended_assay_count": recommended,
        "optional_assay_count": optional,
        "planning_notice": "Recommended assays are planning support only and are not experimental results.",
    }
    clean_records = [
        {
            "id": r.get("id"),
            "project_id": r.get("project_id"),
            "source_type": r.get("source_type"),
            "candidate_count": r.get("candidate_count"),
            "plan_title": r.get("plan_title"),
            "created_at": r.get("created_at"),
        }
        for r in records
    ]
    return _section("validation_planner", "Experimental Validation Planner", payload.include_validation_planner, clean_records, summary)


def _experimental_feedback_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    batches = _rows("experimental_result_batches", payload.project_id, limit=50)
    feedback = _rows("prediction_feedback_summaries", payload.project_id, limit=50)
    supported = contradicted = inconclusive = not_comparable = 0
    for row in feedback:
        agreement = _json_loads(row.get("agreement_summary_json"), {})
        supported += int(agreement.get("supported_count") or 0)
        contradicted += int(agreement.get("contradicted_count") or 0)
        inconclusive += int(agreement.get("inconclusive_count") or 0)
        not_comparable += int(agreement.get("not_comparable_count") or 0)
    summary = {
        "result_batch_count": len(batches),
        "feedback_summary_count": len(feedback),
        "supported_count": supported,
        "contradicted_count": contradicted,
        "inconclusive_count": inconclusive,
        "not_comparable_count": not_comparable,
        "no_fake_results_statement": "No experimental results are generated by this report.",
    }
    clean_batches = [
        {
            "id": r.get("id"),
            "project_id": r.get("project_id"),
            "validation_plan_id": r.get("validation_plan_id"),
            "source_type": r.get("source_type"),
            "result_count": r.get("result_count"),
            "accepted_count": r.get("accepted_count"),
            "rejected_count": r.get("rejected_count"),
            "created_at": r.get("created_at"),
        }
        for r in batches
    ]
    clean_feedback = [
        {
            "id": r.get("id"),
            "project_id": r.get("project_id"),
            "result_batch_id": r.get("result_batch_id"),
            "linked_model_id": r.get("linked_model_id"),
            "linked_prioritization_run_id": r.get("linked_prioritization_run_id"),
            "linked_validation_plan_id": r.get("linked_validation_plan_id"),
            "created_at": r.get("created_at"),
        }
        for r in feedback
    ]
    return _section("experimental_feedback", "Experimental Results Feedback", payload.include_experimental_feedback, clean_batches + clean_feedback, summary)


def _project_context(project_id: int | None) -> dict[str, Any]:
    if not project_id:
        return {"project": None, "dashboard": None, "warnings": ["No project was selected; report summarizes available stored records."]}
    dashboard = project_dashboard(project_id).model_dump()
    return {"project": dashboard.get("project"), "dashboard": dashboard, "warnings": dashboard.get("warnings", [])}


def _build_payload(request: FinalProjectReportRequest, created_at: str) -> dict[str, Any]:
    context = _project_context(request.project_id)
    sections = [
        _screening_section(request),
        _training_section(request),
        _prediction_section(request),
        _external_validation_section(request),
        _domain_section(request),
        _explainability_section(request),
        _lead_section(request),
        _validation_planner_section(request),
        _experimental_feedback_section(request),
    ]
    included = [section.section_id for section in sections if section.included]
    missing = [section.section_id for section in sections if not section.included and section.summary.get("status") != "not requested"]
    warnings = list(context.get("warnings") or [])
    project_items = ((context.get("project") or {}).get("items") or []) if isinstance(context.get("project"), dict) else []
    if any((item.get("metadata") or {}).get("demo_mode") or (item.get("metadata") or {}).get("data_source") == "demo" or "demo" in str(item.get("item_type", "")) for item in project_items):
        warnings.append("Demo data for software demonstration only. Not experimental or clinical evidence.")
    for section in sections:
        warnings.extend(section.warnings)
    active_model = get_active_trained_model_info()
    evidence_missing = []
    by_id = {section.section_id: section for section in sections}
    if request.include_admet_prediction and not active_model:
        evidence_missing.append("active_trained_model")
        warnings.append("No active trained ADMET model was available for this report.")
    external_section = by_id.get("external_validation")
    if request.include_external_validation and not (external_section and external_section.summary.get("external_validation_run_count", 0)):
        evidence_missing.append("external_validation")
        warnings.append("External validation/calibration was not available for this project.")
    feedback_section = by_id.get("experimental_feedback")
    if request.include_experimental_feedback and not (feedback_section and feedback_section.summary.get("result_batch_count", 0)):
        evidence_missing.append("experimental_feedback")
        warnings.append("No user-entered experimental results were imported. Experimental feedback comparison was not performed.")
    validation_section = by_id.get("validation_planner")
    if request.include_validation_planner and not (validation_section and validation_section.summary.get("validation_plan_count", 0)):
        evidence_missing.append("validation_planner")
    missing = list(dict.fromkeys([*missing, *evidence_missing]))
    screening_count = next((section.summary.get("screening_run_count", 0) for section in sections if section.section_id == "screening"), 0)
    lead_top = next((section.summary.get("top_candidates", []) for section in sections if section.section_id == "lead_prioritization"), [])
    dashboard = context.get("dashboard") or {}
    next_steps = list(dashboard.get("recommended_next_steps") or [])
    if not next_steps:
        next_steps = [
            "Complete missing data before relying on computational summaries.",
            "Run or review experimental validation assays for candidates kept under consideration.",
            "Use model retraining only when enough curated and validated experimental data exists.",
        ]
    summary = FinalProjectReportSummary(
        project_name=(context.get("project") or {}).get("title") if context.get("project") else None,
        generated_at=created_at,
        molecule_or_candidate_count=int(screening_count or len(dashboard.get("candidate_matrix") or [])),
        top_candidates=lead_top[:5],
        main_findings=[
            f"Included sections: {', '.join(included) or 'none'}",
            f"Missing sections: {', '.join(missing) or 'none'}",
        ],
        main_warnings=list(dict.fromkeys(warnings))[:20],
        next_recommended_steps=next_steps,
    )
    concise = _concise_report(request, context, sections, created_at)
    return {
        "report_title": request.report_title,
        "project_id": request.project_id,
        "created_at": created_at,
        "app_version": app_version(),
        "scientific_notice": SCIENTIFIC_NOTICE,
        "executive_summary": summary.model_dump(),
        "concise_report": concise,
        "project_context": context,
        "sections": [section.model_dump() for section in sections],
        "included_sections": included,
        "missing_sections": missing,
        "final_limitations": FINAL_LIMITATIONS,
        "reproducibility": {
            "app_version": app_version(),
            "python_version": sys.version.split()[0],
            "python_implementation": platform.python_implementation(),
            "run_command": ".\\scripts\\start_all.ps1",
            "test_command": ".\\scripts\\run_tests.ps1",
            "generated_at": created_at,
        },
        "warnings": list(dict.fromkeys(warnings)),
    }


def _pdf_table(rows: list[list[str]], widths: list[float] | None = None) -> Table:
    wrapped_rows = [[Paragraph(escape(_text(cell, 500)), getSampleStyleSheet()["BodyText"]) for cell in row] for row in rows]
    table = Table(wrapped_rows, colWidths=widths or [2.0 * inch, 4.6 * inch], repeatRows=1 if len(rows) > 1 else 0)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef2f5")),
                ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#c8d1dc")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("FONTSIZE", (0, 0), (-1, -1), 7.2),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    return table


def _pairs(mapping: dict[str, Any]) -> list[list[str]]:
    return [["Field", "Value"], *[[key.replace("_", " ").title(), _text(value, 700)] for key, value in mapping.items()]]


def _docx_table(document, headers: list[str], rows: list[list[Any]]) -> None:
    table = document.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"
    for idx, header in enumerate(headers):
        table.rows[0].cells[idx].text = _text(header, 120)
    for row in rows:
        cells = table.add_row().cells
        for idx, value in enumerate(row[: len(headers)]):
            cells[idx].text = _text(value, 700)
    document.add_paragraph("")


def _project_items(context: dict[str, Any]) -> list[dict[str, Any]]:
    project = context.get("project") if isinstance(context.get("project"), dict) else {}
    return list(project.get("items") or [])


def _latest_item_of_type(context: dict[str, Any], *item_types: str) -> dict[str, Any] | None:
    for item in _project_items(context):
        if item.get("item_type") in item_types:
            return item
    return None


def _candidate_source_label(context: dict[str, Any]) -> str:
    items = _project_items(context)
    text = " ".join(str(item) for item in items).lower()
    if "demo" in text:
        return "Demo/local records labelled for software demonstration only."
    if "known" in text or "fallback" in text:
        return "Known compound or local fallback data was used where external discovery was unavailable."
    if any(item.get("item_type") in {"chembl_candidate", "drug_finder_batch"} for item in items):
        return "External candidate discovery records were attached to this project."
    return "No candidate discovery source was clearly recorded for this project."


def _completion_statuses(sections: list[FinalProjectReportSection], context: dict[str, Any], active_model: Any) -> list[dict[str, str]]:
    dashboard = context.get("dashboard") or {}
    item_counts = dashboard.get("item_counts") or {}
    matrix = dashboard.get("candidate_matrix") or []
    section_by_id = {section.section_id: section for section in sections}
    validation = section_by_id.get("validation_planner")
    feedback = section_by_id.get("experimental_feedback")
    external = section_by_id.get("external_validation")
    return [
        {"step": "Disease/target matching", "status": "Included" if context.get("project") else "Not available", "notes": "Project target context was available." if context.get("project") else "No project context was selected."},
        {"step": "Candidate discovery/fallback", "status": "Included" if matrix or item_counts else "Not available", "notes": _candidate_source_label(context)},
        {"step": "Similarity expansion", "status": "Included" if item_counts.get("similarity_analog") or item_counts.get("similarity_batch") else "Not run", "notes": "Similarity records are included only if attached to this project."},
        {"step": "Screening + ADMET profiling", "status": "Included" if matrix else "Not available", "notes": "Descriptor/rule-based evidence is shown for candidates with saved screening data."},
        {"step": "Lead prioritization", "status": "Included" if item_counts.get("admet_lead_prioritization") or (section_by_id.get("lead_prioritization") and section_by_id["lead_prioritization"].included) else "Not run", "notes": "Priority labels are conservative computational review labels."},
        {"step": "Validation planner", "status": "Included" if validation and validation.summary.get("validation_plan_count", 0) else "Not available", "notes": "Planning support only; no assay results are implied."},
        {"step": "Experimental feedback", "status": "Included" if feedback and feedback.summary.get("result_batch_count", 0) else "Not available", "notes": "No user-entered experimental results were imported." if not (feedback and feedback.summary.get("result_batch_count", 0)) else "User-entered/imported results were found."},
        {"step": "External validation", "status": "Included" if external and external.summary.get("external_validation_run_count", 0) else "Not available", "notes": "External validation/calibration was not available for this project." if not (external and external.summary.get("external_validation_run_count", 0)) else "External validation records were found."},
        {"step": "Active trained ADMET model", "status": "Included" if active_model else "Not available", "notes": "No active trained ADMET model was available for this report." if not active_model else "Active trained model metadata was available."},
        {"step": "Final report", "status": "Included", "notes": "Report generated from available project-scoped data."},
    ]


def _top_candidate_rows(context: dict[str, Any]) -> list[dict[str, Any]]:
    dashboard = context.get("dashboard") or {}
    rows = list(dashboard.get("candidate_matrix") or [])
    if not rows:
        return []
    priority_order = {
        "Strong follow-up candidate": 0,
        "Reasonable follow-up candidate": 1,
        "Review with caution": 2,
        "Insufficient evidence": 3,
        "Not recommended based on available data": 4,
    }
    rows.sort(key=lambda row: (priority_order.get(row.get("decision_label"), 9), len(row.get("missing_data_warnings") or [])))
    return rows[:5]


def _candidate_table_rows(candidates: list[dict[str, Any]]) -> list[list[str]]:
    rows = [["Rank", "Compound", "Source", "Priority label", "Score", "Lipinski", "Veber", "ADMET concern", "Evidence", "Missing evidence", "Next step"]]
    for idx, candidate in enumerate(candidates, start=1):
        missing = candidate.get("missing_data_warnings") or []
        rows.append([
            str(idx),
            _text(candidate.get("candidate_name"), 80),
            _text(candidate.get("source_workflow"), 70),
            _text(candidate.get("decision_label"), 80),
            _text(_first_available(candidate.get("evidence_score"), "not available"), 40),
            _text(candidate.get("lipinski_status"), 50),
            _text(candidate.get("veber_status"), 50),
            _text(candidate.get("admet_risk_summary"), 70),
            _text(candidate.get("evidence_level"), 70),
            _text("; ".join(missing[:2]) if missing else "none noted", 140),
            _text(candidate.get("decision_reason"), 150),
        ])
    return rows


def _admet_rows(candidates: list[dict[str, Any]]) -> list[list[str]]:
    rows = [["Compound", "MW", "LogP", "TPSA", "HBD", "HBA", "Rotatable bonds", "Lipinski", "Veber", "Rule-based ADMET concern"]]
    for candidate in candidates:
        rows.append([
            _text(candidate.get("candidate_name"), 80),
            _text(candidate.get("molecular_weight"), 35),
            _text(candidate.get("logp"), 35),
            _text(candidate.get("tpsa"), 35),
            "not available",
            "not available",
            "not available",
            _text(candidate.get("lipinski_status"), 50),
            _text(candidate.get("veber_status"), 50),
            _text(candidate.get("admet_risk_summary"), 70),
        ])
    return rows


def _top_candidate_explanations(candidates: list[dict[str, Any]]) -> list[str]:
    explanations = []
    for candidate in candidates[:5]:
        name = _text(candidate.get("candidate_name"), 80)
        label = _text(candidate.get("decision_label"), 80)
        lipinski = _text(candidate.get("lipinski_status"), 40)
        veber = _text(candidate.get("veber_status"), 40)
        admet = _text(candidate.get("admet_risk_summary"), 50)
        missing = candidate.get("missing_data_warnings") or []
        missing_text = _text("; ".join(missing[:3]) if missing else "No major missing descriptor fields were flagged in the saved project matrix.", 220)
        explanations.append(
            f"{name} was classified as '{label}' using available computational project data. "
            f"Lipinski status: {lipinski}; Veber status: {veber}; rule-based ADMET concern: {admet}. "
            f"Missing evidence: {missing_text}. This is not evidence of efficacy against the selected disease or target. "
            "Experimental validation and expert review are required."
        )
    return explanations


def _concise_report(request: FinalProjectReportRequest, context: dict[str, Any], sections: list[FinalProjectReportSection], created_at: str) -> dict[str, Any]:
    project = context.get("project") if isinstance(context.get("project"), dict) else {}
    active_model = get_active_trained_model_info()
    top_candidates = _top_candidate_rows(context)
    latest_candidate = top_candidates[0] if top_candidates else {}
    validation_section = next((section for section in sections if section.section_id == "validation_planner"), None)
    feedback_section = next((section for section in sections if section.section_id == "experimental_feedback"), None)
    external_section = next((section for section in sections if section.section_id == "external_validation"), None)
    known_item = _latest_item_of_type(context, "chembl_candidate", "screening", "drug_finder_batch", "similarity_batch", "batch_screening")
    known_metadata = known_item.get("metadata") if known_item else {}
    workflow_inputs = {
        "Disease": project.get("disease_area") or "not available",
        "Target": project.get("target_name") or "not available",
        "Known compound": known_metadata.get("compound_name") or known_metadata.get("candidate_name") or "not available",
        "Candidate limit": known_metadata.get("candidate_limit") or "not available",
        "Similarity limit": known_metadata.get("similarity_limit") or "not available",
        "Analysis depth": known_metadata.get("analysis_depth") or "not available",
        "Project ID": request.project_id or "not available",
        "Data source status": _candidate_source_label(context),
    }
    missing_evidence = []
    if not active_model:
        missing_evidence.append("No active trained ADMET model was available for this report.")
    if not (external_section and external_section.summary.get("external_validation_run_count", 0)):
        missing_evidence.append("External validation/calibration was not available for this project.")
    if not (feedback_section and feedback_section.summary.get("result_batch_count", 0)):
        missing_evidence.append("No user-entered experimental results were imported. Experimental feedback comparison was not performed.")
    if not top_candidates:
        missing_evidence.append("No project-scoped candidate matrix rows were available.")
    validation_summary = {
        "essential_assay_count": (validation_section.summary.get("essential_assay_count", 0) if validation_section else 0),
        "recommended_assay_count": (validation_section.summary.get("recommended_assay_count", 0) if validation_section else 0),
        "optional_assay_count": (validation_section.summary.get("optional_assay_count", 0) if validation_section else 0),
        "top_recommended_assays": ["Review validation planner output for project-specific assays."] if validation_section and validation_section.summary.get("validation_plan_count", 0) else [],
        "notice": "Experimental planning support only. Actual assay design must be reviewed by qualified laboratory personnel.",
    }
    next_steps = list((context.get("dashboard") or {}).get("recommended_next_steps") or [])
    if not next_steps:
        next_steps = [
            "Validate top candidates experimentally using qualified laboratory protocols.",
            "Confirm target relevance with literature and expert review.",
            "Run real ADMET assays and import experimental feedback after testing.",
            "Re-run this report after real validation data are added.",
        ]
    return {
        "title_page": {
            "report_title": request.report_title,
            "project_name": project.get("title") or "not available",
            "disease": workflow_inputs["Disease"],
            "target": workflow_inputs["Target"],
            "known_compound": workflow_inputs["Known compound"],
            "generated_date": created_at,
            "scientific_disclaimer": SCIENTIFIC_NOTICE,
        },
        "executive_summary_bullets": [
            f"Analyzed project: {project.get('title') or 'not available'}; disease: {workflow_inputs['Disease']}; target: {workflow_inputs['Target']}.",
            f"Candidate rows evaluated in this project report: {len((context.get('dashboard') or {}).get('candidate_matrix') or [])}.",
            f"Top candidate for review: {_text(latest_candidate.get('candidate_name') if latest_candidate else None)}.",
            f"Main computational finding: {_text(latest_candidate.get('decision_reason') if latest_candidate else 'Candidate-level evidence was limited or unavailable.', 260)}",
            f"Main missing evidence: {_text('; '.join(missing_evidence), 320)}",
            f"Recommended next step: {_text(next_steps[0] if next_steps else None, 220)}",
        ],
        "workflow_input_summary": workflow_inputs,
        "workflow_completion_summary": _completion_statuses(sections, context, active_model),
        "candidate_discovery_summary": {
            "source_status": _candidate_source_label(context),
            "friendly_warning": "External candidate discovery may be unavailable; known/local fallback data can be used where clearly labelled.",
        },
        "top_candidate_table": _candidate_table_rows(top_candidates),
        "top_candidate_explanations": _top_candidate_explanations(top_candidates),
        "admet_descriptor_summary": _admet_rows(top_candidates),
        "model_evidence_summary": {
            "status": "available" if active_model else "not available",
            "message": "Active trained model evidence was available." if active_model else "No active trained ADMET model was available for this report. Trained model evidence was not available; rule-based descriptor evidence was used.",
        },
        "external_validation_summary": {
            "status": "available" if external_section and external_section.summary.get("external_validation_run_count", 0) else "not available",
            "message": "External validation/calibration was not available for this project." if not (external_section and external_section.summary.get("external_validation_run_count", 0)) else "External validation records were available.",
        },
        "experimental_feedback_summary": {
            "status": "available" if feedback_section and feedback_section.summary.get("result_batch_count", 0) else "not available",
            "message": "No user-entered experimental results were imported. Experimental feedback comparison was not performed." if not (feedback_section and feedback_section.summary.get("result_batch_count", 0)) else "User-entered/imported experimental feedback records were available.",
        },
        "validation_planner_summary": validation_summary,
        "final_limitations": FINAL_LIMITATIONS,
        "recommended_next_steps": next_steps,
    }


def _build_pdf(payload: dict[str, Any]) -> bytes:
    buffer = BytesIO()
    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=0.45 * inch, leftMargin=0.45 * inch)
    concise = payload["concise_report"]
    title = concise["title_page"]
    story = [Paragraph(escape(payload["report_title"]), styles["Title"]), Paragraph(escape(payload["scientific_notice"]), styles["BodyText"]), Spacer(1, 10)]
    story.append(Paragraph("Title Page", styles["Heading2"]))
    story.append(_pdf_table(_pairs(title)))
    story.append(Paragraph("Executive Summary", styles["Heading2"]))
    for bullet in concise["executive_summary_bullets"]:
        story.append(Paragraph(f"- {escape(_text(bullet, 650))}", styles["BodyText"]))
    story.append(Paragraph("Workflow Input Summary", styles["Heading2"]))
    story.append(_pdf_table(_pairs(concise["workflow_input_summary"])))
    story.append(Paragraph("Workflow Completion Summary", styles["Heading2"]))
    story.append(_pdf_table([["Step", "Status", "Notes"], *[[row["step"], row["status"], row["notes"]] for row in concise["workflow_completion_summary"]]], [1.55 * inch, 1.0 * inch, 4.0 * inch]))
    story.append(Paragraph("Candidate Discovery Summary", styles["Heading2"]))
    story.append(_pdf_table(_pairs(concise["candidate_discovery_summary"])))
    story.append(Paragraph("Top Candidate Table", styles["Heading2"]))
    story.append(_pdf_table(concise["top_candidate_table"], [0.35 * inch, 0.9 * inch, 0.7 * inch, 0.85 * inch, 0.45 * inch, 0.55 * inch, 0.55 * inch, 0.75 * inch, 0.65 * inch, 0.85 * inch, 0.9 * inch]))
    story.append(Paragraph("Top Candidate Explanation", styles["Heading2"]))
    for explanation in concise["top_candidate_explanations"] or ["No project-scoped top candidate was available."]:
        story.append(Paragraph(f"- {escape(_text(explanation, 900))}", styles["BodyText"]))
    story.append(Paragraph("ADMET & Drug-Likeness Summary", styles["Heading2"]))
    story.append(_pdf_table(concise["admet_descriptor_summary"], [0.9 * inch, 0.45 * inch, 0.45 * inch, 0.45 * inch, 0.45 * inch, 0.45 * inch, 0.65 * inch, 0.65 * inch, 0.55 * inch, 1.0 * inch]))
    story.append(Paragraph("Model Evidence Summary", styles["Heading2"]))
    story.append(_pdf_table(_pairs(concise["model_evidence_summary"])))
    story.append(Paragraph("External Validation Summary", styles["Heading2"]))
    story.append(_pdf_table(_pairs(concise["external_validation_summary"])))
    story.append(Paragraph("Experimental Feedback Summary", styles["Heading2"]))
    story.append(_pdf_table(_pairs(concise["experimental_feedback_summary"])))
    story.append(Paragraph("Validation Planner Summary", styles["Heading2"]))
    story.append(_pdf_table(_pairs(concise["validation_planner_summary"])))
    story.append(Paragraph("Final Limitations", styles["Heading2"]))
    for item in payload["final_limitations"]:
        story.append(Paragraph(f"- {escape(_text(item, 700))}", styles["BodyText"]))
    story.append(Paragraph("Recommended Next Steps", styles["Heading2"]))
    for item in concise["recommended_next_steps"]:
        story.append(Paragraph(f"- {escape(_text(item, 700))}", styles["BodyText"]))
    story.append(Paragraph("Reproducibility", styles["Heading2"]))
    story.append(_pdf_table(_pairs(payload["reproducibility"])))
    doc.build(story)
    return buffer.getvalue()


def _build_docx(payload: dict[str, Any]) -> bytes:
    document = Document()
    concise = payload["concise_report"]
    title = concise["title_page"]
    document.add_heading(payload["report_title"], 0)
    document.add_paragraph(payload["scientific_notice"])
    document.add_heading("Title Page", level=1)
    _docx_table(document, ["Field", "Value"], [[key.replace("_", " ").title(), _text(value)] for key, value in title.items()])
    document.add_heading("Executive Summary", level=1)
    for bullet in concise["executive_summary_bullets"]:
        document.add_paragraph(_text(bullet, 800), style="List Bullet")
    document.add_heading("Workflow Input Summary", level=1)
    _docx_table(document, ["Field", "Value"], [[key, _text(value)] for key, value in concise["workflow_input_summary"].items()])
    document.add_heading("Workflow Completion Summary", level=1)
    _docx_table(document, ["Step", "Status", "Notes"], [[row["step"], row["status"], row["notes"]] for row in concise["workflow_completion_summary"]])
    document.add_heading("Candidate Discovery Summary", level=1)
    _docx_table(document, ["Field", "Value"], [[key.replace("_", " ").title(), _text(value)] for key, value in concise["candidate_discovery_summary"].items()])
    document.add_heading("Top Candidate Table", level=1)
    _docx_table(document, concise["top_candidate_table"][0], concise["top_candidate_table"][1:])
    document.add_heading("Top Candidate Explanation", level=1)
    for explanation in concise["top_candidate_explanations"] or ["No project-scoped top candidate was available."]:
        document.add_paragraph(_text(explanation, 1000), style="List Bullet")
    document.add_heading("ADMET & Drug-Likeness Summary", level=1)
    _docx_table(document, concise["admet_descriptor_summary"][0], concise["admet_descriptor_summary"][1:])
    document.add_heading("Model Evidence Summary", level=1)
    _docx_table(document, ["Field", "Value"], [[key.replace("_", " ").title(), _text(value)] for key, value in concise["model_evidence_summary"].items()])
    document.add_heading("External Validation Summary", level=1)
    _docx_table(document, ["Field", "Value"], [[key.replace("_", " ").title(), _text(value)] for key, value in concise["external_validation_summary"].items()])
    document.add_heading("Experimental Feedback Summary", level=1)
    _docx_table(document, ["Field", "Value"], [[key.replace("_", " ").title(), _text(value)] for key, value in concise["experimental_feedback_summary"].items()])
    document.add_heading("Validation Planner Summary", level=1)
    _docx_table(document, ["Field", "Value"], [[key.replace("_", " ").title(), _text(value)] for key, value in concise["validation_planner_summary"].items()])
    document.add_heading("Final Limitations", level=1)
    for item in payload["final_limitations"]:
        document.add_paragraph(item, style="List Bullet")
    document.add_heading("Recommended Next Steps", level=1)
    for item in concise["recommended_next_steps"]:
        document.add_paragraph(item, style="List Bullet")
    document.add_heading("Reproducibility", level=1)
    for key, value in payload["reproducibility"].items():
        document.add_paragraph(f"{key.replace('_', ' ').title()}: {_safe(value)}")
    buffer = BytesIO()
    document.save(buffer)
    return buffer.getvalue()


def _save_report(request: FinalProjectReportRequest, payload: dict[str, Any], files: dict[str, str]) -> int:
    summary_record = dict(payload["executive_summary"])
    summary_record["missing_sections"] = payload["missing_sections"]
    init_db()
    with get_connection() as connection:
        cursor = connection.execute(
            """
            INSERT INTO final_project_reports (
                project_id, report_title, included_sections_json, summary_json,
                warnings_json, files_json
            )
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                request.project_id,
                request.report_title,
                json.dumps(payload["included_sections"]),
                json.dumps(summary_record),
                json.dumps(payload["warnings"]),
                json.dumps(files),
            ),
        )
        report_id = int(cursor.lastrowid)
    return report_id


def create_final_project_report(request: FinalProjectReportRequest) -> FinalProjectReportResponse:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    created = _now()
    created_at = created.isoformat()
    stamp = _timestamp(created)
    payload = _build_payload(request, created_at)
    base = f"final_project_report_{request.project_id or 'global'}_{stamp}"
    files: dict[str, str] = {}
    requested_formats = set(request.formats or ["json"])
    if "json" in requested_formats:
        name = f"{base}.json"
        (REPORT_DIR / name).write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")
        files["json"] = name
    if "pdf" in requested_formats:
        name = f"{base}.pdf"
        (REPORT_DIR / name).write_bytes(_build_pdf(payload))
        files["pdf"] = name
    if "docx" in requested_formats:
        name = f"{base}.docx"
        (REPORT_DIR / name).write_bytes(_build_docx(payload))
        files["docx"] = name
    report_id = _save_report(request, payload, files)
    if request.project_id:
        try:
            attach_project_item(
                request.project_id,
                ProjectAttachRequest(
                    item_type="final_project_report",
                    item_id=str(report_id),
                    item_title=request.report_title,
                    metadata={
                        "workflow_type": "final_end_to_end_report",
                        "report_id": report_id,
                        "included_sections": payload["included_sections"],
                        "missing_sections": payload["missing_sections"],
                        "scientific_notice": SCIENTIFIC_NOTICE,
                    },
                ),
            )
        except Exception:
            pass
    return FinalProjectReportResponse(
        report_id=report_id,
        report_title=request.report_title,
        project_id=request.project_id,
        generated_files={fmt: f"/api/final-report/reports/{report_id}/{fmt}" for fmt in files},
        included_sections=payload["included_sections"],
        missing_sections=payload["missing_sections"],
        warnings=payload["warnings"],
        scientific_notice=SCIENTIFIC_NOTICE,
        created_at=created_at,
    )


def _report_row(report_id: int) -> Any:
    init_db()
    with get_connection() as connection:
        row = connection.execute("SELECT * FROM final_project_reports WHERE id = ?", (report_id,)).fetchone()
    if not row:
        raise HTTPException(status_code=404, detail="Final project report not found.")
    return row


def get_final_project_report(report_id: int) -> FinalProjectReportResponse:
    row = _report_row(report_id)
    files = _json_loads(row["files_json"], {})
    included = _json_loads(row["included_sections_json"], [])
    summary = _json_loads(row["summary_json"], {})
    warnings = _json_loads(row["warnings_json"], [])
    return FinalProjectReportResponse(
        report_id=row["id"],
        report_title=row["report_title"],
        project_id=row["project_id"],
        generated_files={fmt: f"/api/final-report/reports/{row['id']}/{fmt}" for fmt in files},
        included_sections=included,
        missing_sections=summary.get("missing_sections", []),
        warnings=warnings,
        scientific_notice=SCIENTIFIC_NOTICE,
        created_at=row["created_at"],
    )


def list_final_project_reports() -> list[dict[str, Any]]:
    init_db()
    with get_connection() as connection:
        rows = connection.execute("SELECT * FROM final_project_reports ORDER BY datetime(created_at) DESC, id DESC LIMIT 50").fetchall()
    return [
        {
            "report_id": row["id"],
            "project_id": row["project_id"],
            "report_title": row["report_title"],
            "included_sections": _json_loads(row["included_sections_json"], []),
            "warnings": _json_loads(row["warnings_json"], []),
            "generated_files": {fmt: f"/api/final-report/reports/{row['id']}/{fmt}" for fmt in _json_loads(row["files_json"], {})},
            "created_at": row["created_at"],
        }
        for row in rows
    ]


def final_report_file_path(report_id: int, file_format: str) -> Path:
    if file_format not in {"json", "pdf", "docx"}:
        raise HTTPException(status_code=404, detail="Unsupported final report format.")
    row = _report_row(report_id)
    files = _json_loads(row["files_json"], {})
    filename = files.get(file_format)
    if not filename:
        raise HTTPException(status_code=404, detail="Final report format was not generated.")
    path = REPORT_DIR / filename
    if not path.exists():
        raise HTTPException(status_code=404, detail="Final report file is missing.")
    return path
