import json
import platform
import sys
from datetime import datetime, timezone
from io import BytesIO
from pathlib import Path
from typing import Any

from docx import Document
from fastapi import HTTPException
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.database import get_connection, init_db
from app.models.final_report_models import (
    FinalProjectReportRequest,
    FinalProjectReportResponse,
    FinalProjectReportSection,
    FinalProjectReportSummary,
)
from app.models.project_workspace_models import ProjectAttachRequest
from app.services.admet_trained_model_service import get_active_trained_model_info
from app.services.local_admet_model import validate_local_admet_model
from app.services.model_registry import model_status_response
from app.services.project_workspace_service import attach_project_item, project_dashboard
from app.services.version import app_version

REPORT_DIR = Path(__file__).resolve().parents[2] / "final_project_reports"
SCIENTIFIC_NOTICE = "Computational decision-support report only. Experimental and clinical interpretation requires qualified scientific review."
FINAL_LIMITATIONS = [
    "This report summarizes stored DrugScreen360 records only; missing data is not inferred.",
    "No experimental result is invented, simulated, or generated by DrugScreen360.",
    "Computational outputs do not prove safety, efficacy, clinical success, regulatory approval, or market readiness.",
    "Applicability-domain, uncertainty, explainability, and model metrics are dataset-dependent.",
    "Qualified scientific review and experimental validation are required before any research decision.",
]


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _timestamp(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%d_%H-%M-%S")


def _safe(value: Any) -> str:
    if value in (None, "", [], {}):
        return "not available"
    if isinstance(value, list):
        items = []
        for item in value:
            if isinstance(item, dict):
                name = item.get("compound_name") or item.get("name") or item.get("model_id") or item.get("task_name")
                if name:
                    items.append(str(name))
            else:
                items.append(str(item))
        if items:
            return ", ".join(items)
        return "not available"
    if isinstance(value, dict):
        pairs = []
        for k, v in value.items():
            if not isinstance(v, (dict, list)):
                pairs.append(f"{k}: {v}")
        if pairs:
            return "; ".join(pairs)
        return "available"
    return str(value)


def _rows(table: str, project_id: int | None = None, limit: int = 100) -> list[dict[str, Any]]:
    init_db()
    with get_connection() as connection:
        if project_id and table in {
            "experimental_validation_plans",
            "experimental_result_batches",
            "prediction_feedback_summaries",
            "admet_lead_prioritization_runs",
        }:
            rows = connection.execute(
                f"SELECT * FROM {table} WHERE project_id = ? ORDER BY datetime(created_at) DESC, id DESC LIMIT ?",
                (project_id, limit),
            ).fetchall()
        else:
            rows = connection.execute(
                f"SELECT * FROM {table} ORDER BY datetime(created_at) DESC, id DESC LIMIT ?",
                (limit,),
            ).fetchall()
    return [dict(row) for row in rows]


def _json_loads(value: Any, default: Any) -> Any:
    if not value:
        return default
    try:
        return json.loads(value)
    except Exception:
        return default


def _section(section_id: str, title: str, requested: bool, records: list[dict[str, Any]], summary: dict[str, Any], warnings: list[str] | None = None) -> FinalProjectReportSection:
    section_warnings = list(warnings or [])
    included = bool(requested and (records or summary))
    if requested and not included:
        section_warnings.append(f"{title} was requested but no stored records were available.")
    return FinalProjectReportSection(
        section_id=section_id,
        title=title,
        included=included,
        summary=summary if requested else {"status": "not requested"},
        records=records if requested else [],
        warnings=section_warnings,
    )


def _screening_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    records = _rows("screening_history", limit=50)
    summary = {
        "screening_run_count": len(records),
        "recent_compounds": [row.get("compound_name") or row.get("input_query") for row in records[:8]],
        "decisions": {},
    }
    for row in records:
        decision = row.get("decision") or "not available"
        summary["decisions"][decision] = summary["decisions"].get(decision, 0) + 1
    clean_records = [
        {
            "id": r.get("id"),
            "input_query": r.get("input_query"),
            "input_type": r.get("input_type"),
            "compound_name": r.get("compound_name"),
            "pubchem_cid": r.get("pubchem_cid"),
            "canonical_smiles": r.get("canonical_smiles"),
            "decision": r.get("decision"),
            "created_at": r.get("created_at"),
        }
        for r in records
    ]
    return _section("screening", "Molecule Screening Summary", payload.include_screening, clean_records, summary)


def _training_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    datasets = _rows("admet_datasets", limit=50)
    runs = _rows("admet_training_runs", limit=50)
    summary = {
        "dataset_count": len(datasets),
        "training_run_count": len(runs),
        "latest_training_runs": [
            {
                "id": row.get("id"),
                "task_type": row.get("task_type"),
                "model_type": row.get("model_type"),
                "status": row.get("status"),
                "metrics": _json_loads(row.get("metric_summary_json"), {}),
            }
            for row in runs[:5]
        ],
    }
    clean_datasets = [
        {
            "id": r.get("id"),
            "name": r.get("name"),
            "task_name": r.get("task_name"),
            "label_column": r.get("label_column"),
            "original_filename": r.get("original_filename"),
            "record_count": r.get("record_count"),
            "valid_count": r.get("valid_count"),
            "invalid_count": r.get("invalid_count"),
            "duplicate_count": r.get("duplicate_count"),
            "status": r.get("status"),
            "created_at": r.get("created_at"),
        }
        for r in datasets
    ]
    clean_runs = [
        {
            "id": r.get("id"),
            "dataset_id": r.get("dataset_id"),
            "task_name": r.get("task_name"),
            "task_type": r.get("task_type"),
            "model_name": r.get("model_name"),
            "model_type": r.get("model_type"),
            "status": r.get("status"),
            "train_count": r.get("train_count"),
            "test_count": r.get("test_count"),
            "created_at": r.get("created_at"),
        }
        for r in runs
    ]
    return _section("model_training", "ADMET Dataset & Training Summary", payload.include_model_training, clean_datasets + clean_runs, summary)


def _prediction_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    model_status = model_status_response()
    active = get_active_trained_model_info()
    logs = _rows("model_prediction_logs", limit=50)
    summary = {
        "active_trained_model": active,
        "available_models": [item.model_dump() for item in model_status["available_models"]],
        "unavailable_models": [item.model_dump() for item in model_status["unavailable_models"]],
        "prediction_log_count": len(logs),
    }
    clean_logs = [
        {
            "id": r.get("id"),
            "smiles": r.get("smiles"),
            "model_id": r.get("model_id"),
            "task_name": r.get("task_name"),
            "prediction_label": r.get("prediction_label"),
            "prediction_score": r.get("prediction_score"),
            "confidence": r.get("confidence"),
            "status": r.get("status"),
            "created_at": r.get("created_at"),
        }
        for r in logs
    ]
    return _section("admet_prediction", "Trained Model Prediction Summary", payload.include_admet_prediction, clean_logs, summary)


def _external_validation_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    records = _rows("admet_external_validation_runs", limit=50)
    summary = {
        "external_validation_run_count": len(records),
        "latest_status": records[0].get("status") if records else "not available",
        "latest_metrics": _json_loads(records[0].get("metric_summary_json"), {}) if records else {},
    }
    clean_records = [
        {
            "id": r.get("id"),
            "model_id": r.get("model_id"),
            "training_run_id": r.get("training_run_id"),
            "external_dataset_id": r.get("external_dataset_id"),
            "task_name": r.get("task_name"),
            "task_type": r.get("task_type"),
            "status": r.get("status"),
            "valid_count": r.get("valid_count"),
            "invalid_count": r.get("invalid_count"),
            "created_at": r.get("created_at"),
        }
        for r in records
    ]
    return _section("external_validation", "External Validation & Calibration", payload.include_external_validation, clean_records, summary)


def _domain_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    records = _rows("admet_domain_evaluations", limit=100)
    counts: dict[str, int] = {}
    uncertainty: dict[str, int] = {}
    for row in records:
        counts[row.get("domain_status") or "unknown"] = counts.get(row.get("domain_status") or "unknown", 0) + 1
        uncertainty[row.get("uncertainty_level") or "unknown"] = uncertainty.get(row.get("uncertainty_level") or "unknown", 0) + 1
    summary = {"domain_status_counts": counts, "uncertainty_distribution": uncertainty, "evaluation_count": len(records)}
    clean_records = [
        {
            "id": r.get("id"),
            "model_id": r.get("model_id"),
            "training_run_id": r.get("training_run_id"),
            "smiles": r.get("smiles"),
            "canonical_smiles": r.get("canonical_smiles"),
            "domain_status": r.get("domain_status"),
            "uncertainty_level": r.get("uncertainty_level"),
            "created_at": r.get("created_at"),
        }
        for r in records
    ]
    return _section("applicability_domain", "Applicability Domain & Uncertainty", payload.include_applicability_domain, clean_records, summary)


def _explainability_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    records = _rows("admet_prediction_explanations", limit=50)
    evidence: dict[str, int] = {}
    for row in records:
        evidence[row.get("evidence_strength") or "unknown"] = evidence.get(row.get("evidence_strength") or "unknown", 0) + 1
    summary = {
        "explanation_count": len(records),
        "evidence_strength_distribution": evidence,
        "causality_notice": "Feature importance and coefficients are model diagnostics, not biological causality.",
    }
    clean_records = [
        {
            "id": r.get("id"),
            "model_id": r.get("model_id"),
            "training_run_id": r.get("training_run_id"),
            "smiles": r.get("smiles"),
            "canonical_smiles": r.get("canonical_smiles"),
            "evidence_strength": r.get("evidence_strength"),
            "domain_status": r.get("domain_status"),
            "uncertainty_level": r.get("uncertainty_level"),
            "created_at": r.get("created_at"),
        }
        for r in records
    ]
    return _section("explainability", "Prediction Explainability", payload.include_explainability, clean_records, summary)


def _lead_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    records = _rows("admet_lead_prioritization_runs", payload.project_id, limit=50)
    top_candidates = []
    for row in records[:5]:
        summary_json = _json_loads(row.get("summary_json"), {})
        top_candidates.extend((summary_json.get("ranked_candidates") or [])[:3])
    summary = {
        "lead_run_count": len(records),
        "top_candidates": top_candidates[:10],
        "priority_label_counts": {},
    }
    for candidate in top_candidates:
        label = candidate.get("priority_label") or "not available"
        summary["priority_label_counts"][label] = summary["priority_label_counts"].get(label, 0) + 1
    clean_records = [
        {
            "id": r.get("id"),
            "project_id": r.get("project_id"),
            "source_type": r.get("source_type"),
            "candidate_count": r.get("candidate_count"),
            "ranked_count": r.get("ranked_count"),
            "excluded_count": r.get("excluded_count"),
            "scoring_profile": r.get("scoring_profile"),
            "created_at": r.get("created_at"),
        }
        for r in records
    ]
    return _section("lead_prioritization", "Lead Prioritization", payload.include_lead_prioritization, clean_records, summary)


def _validation_planner_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    records = _rows("experimental_validation_plans", payload.project_id, limit=50)
    essential = recommended = optional = 0
    for row in records:
        summary_json = _json_loads(row.get("summary_json"), {})
        for candidate in summary_json.get("candidate_plans", []):
            for assay in candidate.get("recommended_assays", []):
                if assay.get("recommendation_priority") == "essential":
                    essential += 1
                elif assay.get("recommendation_priority") == "recommended":
                    recommended += 1
                elif assay.get("recommendation_priority") == "optional":
                    optional += 1
    summary = {
        "validation_plan_count": len(records),
        "essential_assay_count": essential,
        "recommended_assay_count": recommended,
        "optional_assay_count": optional,
        "planning_notice": "Recommended assays are planning support only and are not experimental results.",
    }
    clean_records = [
        {
            "id": r.get("id"),
            "project_id": r.get("project_id"),
            "source_type": r.get("source_type"),
            "candidate_count": r.get("candidate_count"),
            "plan_title": r.get("plan_title"),
            "created_at": r.get("created_at"),
        }
        for r in records
    ]
    return _section("validation_planner", "Experimental Validation Planner", payload.include_validation_planner, clean_records, summary)


def _experimental_feedback_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    batches = _rows("experimental_result_batches", payload.project_id, limit=50)
    feedback = _rows("prediction_feedback_summaries", payload.project_id, limit=50)
    supported = contradicted = inconclusive = not_comparable = 0
    for row in feedback:
        agreement = _json_loads(row.get("agreement_summary_json"), {})
        supported += int(agreement.get("supported_count") or 0)
        contradicted += int(agreement.get("contradicted_count") or 0)
        inconclusive += int(agreement.get("inconclusive_count") or 0)
        not_comparable += int(agreement.get("not_comparable_count") or 0)
    summary = {
        "result_batch_count": len(batches),
        "feedback_summary_count": len(feedback),
        "supported_count": supported,
        "contradicted_count": contradicted,
        "inconclusive_count": inconclusive,
        "not_comparable_count": not_comparable,
        "no_fake_results_statement": "No experimental results are generated by this report.",
    }
    clean_batches = [
        {
            "id": r.get("id"),
            "project_id": r.get("project_id"),
            "validation_plan_id": r.get("validation_plan_id"),
            "source_type": r.get("source_type"),
            "result_count": r.get("result_count"),
            "accepted_count": r.get("accepted_count"),
            "rejected_count": r.get("rejected_count"),
            "created_at": r.get("created_at"),
        }
        for r in batches
    ]
    clean_feedback = [
        {
            "id": r.get("id"),
            "project_id": r.get("project_id"),
            "result_batch_id": r.get("result_batch_id"),
            "linked_model_id": r.get("linked_model_id"),
            "linked_prioritization_run_id": r.get("linked_prioritization_run_id"),
            "linked_validation_plan_id": r.get("linked_validation_plan_id"),
            "created_at": r.get("created_at"),
        }
        for r in feedback
    ]
    return _section("experimental_feedback", "Experimental Results Feedback", payload.include_experimental_feedback, clean_batches + clean_feedback, summary)


def _project_context(project_id: int | None) -> dict[str, Any]:
    if not project_id:
        return {"project": None, "dashboard": None, "warnings": ["No project was selected; report summarizes available stored records."]}
    dashboard = project_dashboard(project_id).model_dump()
    return {"project": dashboard.get("project"), "dashboard": dashboard, "warnings": dashboard.get("warnings", [])}


def _canonical_smiles(smiles: str) -> str | None:
    if not smiles:
        return None
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol:
            return Chem.MolToSmiles(mol, canonical=True)
    except Exception:
        pass
    return None


def _get_dedup_key(c: dict[str, Any]) -> str:
    # 1. RDKit MolFromSmiles + MolToSmiles(canonical=True)
    for smiles_key in ["smiles", "canonical_smiles"]:
        smiles = c.get(smiles_key)
        if smiles:
            canon = _canonical_smiles(smiles)
            if canon:
                return f"smiles:{canon}"
    # Fallback to normalized compound ID/name
    cid = c.get("compound_id")
    if cid:
        return f"id:{str(cid).strip().lower()}"
    name = c.get("compound_name")
    if name:
        return f"name:{str(name).strip().lower()}"
    return f"raw_smiles:{str(c.get('smiles') or '').strip().lower()}"


def _candidate_quality_key(c: dict[str, Any]) -> tuple:
    # 1. Valid canonical_smiles
    has_valid_smiles = 0
    for smiles_key in ["smiles", "canonical_smiles"]:
        smiles = c.get(smiles_key)
        if smiles and _canonical_smiles(smiles):
            has_valid_smiles = 1
            break
            
    # 2. Best rank (lower is better, so negate it)
    rank_val = c.get("rank")
    if rank_val is None:
        rank_val = 999999
    neg_rank = -rank_val
    
    # 3. Most descriptors
    desc_count = len(c.get("descriptors") or {})
    
    # 4. Most score/evidence fields
    score_count = 0
    for comp in ["score_components", "rule_based_admet_summary"]:
        for v in (c.get(comp) or {}).values():
            if v is not None and v != "":
                score_count += 1
    if c.get("trained_model_prediction") is not None:
        score_count += 1
    if c.get("total_score") is not None:
        score_count += 1
        
    # 5. Least missing evidence (negated count)
    neg_missing = -len(c.get("missing_evidence") or [])
    
    return (has_valid_smiles, neg_rank, desc_count, score_count, neg_missing)


def _get_rationale(rationale: str | None) -> str:
    if not rationale or str(rationale).strip() == "" or str(rationale).strip().lower() in ("none", "null"):
        return "Recommended to reduce key uncertainty before experimental follow-up."
    return str(rationale).strip()


def _categorize_assay(assay_name: str) -> str:
    name_lower = str(assay_name).lower()
    if any(x in name_lower for x in ["tox", "safety", "herg", "mutagenicity", "ames", "cytotoxicity", "ld50", "cardio", "hepatotox", "carcinogenicity", "skin"]):
        return "Safety/Toxicity"
    if any(x in name_lower for x in ["caco", "pampa", "permeability", "absorption", "mrd1", "pgp"]):
        return "Permeability/Absorption"
    if any(x in name_lower for x in ["metabolism", "stability", "clearance", "microsomal", "half-life", "cyp", "p450"]):
        return "Metabolism/Stability"
    if any(x in name_lower for x in ["solubility", "logd", "pka", "dissolution"]):
        return "Solubility"
    if any(x in name_lower for x in ["smiles", "identity", "purity", "structure", "mass spec", "nmr", "hplc"]):
        return "Compound identity/data completion"
    return "Safety/Toxicity"  # Default category


def _priority_score(priority: str | None) -> int:
    if not priority:
        return 0
    p = str(priority).strip().lower()
    if p == "essential":
        return 3
    if p == "recommended":
        return 2
    if p == "optional":
        return 1
    return 0


def _generate_candidate_explanation(c: dict[str, Any], scoring_profile: str) -> str:
    name = c.get("compound_name") or c.get("compound_id") or "this candidate"
    score = c.get("total_score") or 0.0
    label = (c.get("priority_label") or "N/A").replace("_", " ").title()
    desc = c.get("descriptors") or {}
    mw = desc.get("molecular_weight")
    logp = desc.get("logp")
    tpsa = desc.get("tpsa")
    
    rules = c.get("rule_based_admet_summary") or {}
    concern_level = rules.get("concern_level", "N/A").replace("_", " ").title()
    
    factors = []
    if mw:
        factors.append(f"MW of {mw} g/mol")
    if logp is not None:
        factors.append(f"LogP of {logp}")
    if tpsa:
        factors.append(f"TPSA of {tpsa} Å²")
        
    pos_factors = c.get("positive_factors") or []
    risk_factors = c.get("risk_factors") or []
    
    explanation = (
        f"{name} is classified as {label} with a total score of {score:.2f} under the {scoring_profile.replace('_', ' ').title()} profile. "
    )
    if factors:
        explanation += f"Physicochemical analysis shows a {', and '.join(factors[:3])}. "
        
    if pos_factors:
        explanation += f"Key strengths include: {', '.join(pos_factors)}. "
        
    if risk_factors:
        explanation += f"Notable concerns identified: {', '.join(risk_factors)}. "
    else:
        explanation += "No major ADMET rules or structural alerts were violated. "
        
    explanation += f"The overall rule-based ADMET concern is evaluated as {concern_level}."
    return explanation


def _build_payload_concise(request: FinalProjectReportRequest, created_at: str) -> dict[str, Any]:
    project_id = request.project_id
    context = _project_context(project_id)
    
    project_title = (context.get("project") or {}).get("title") or "Unknown Project"
    disease_area = (context.get("project") or {}).get("disease_area") or "not available"
    target_name = (context.get("project") or {}).get("target_name") or "not available"

    init_db()
    with get_connection() as connection:
        # 1. Prioritization Run
        run_row = None
        if request.prioritization_run_id:
            run_row = connection.execute(
                "SELECT * FROM admet_lead_prioritization_runs WHERE id = ?",
                (request.prioritization_run_id,)
            ).fetchone()
        elif project_id:
            run_row = connection.execute(
                "SELECT * FROM admet_lead_prioritization_runs WHERE project_id = ? ORDER BY id DESC LIMIT 1",
                (project_id,)
            ).fetchone()

        # 2. Validation Plan
        plan_row = None
        if request.validation_plan_id:
            plan_row = connection.execute(
                "SELECT * FROM experimental_validation_plans WHERE id = ?",
                (request.validation_plan_id,)
            ).fetchone()
        elif project_id:
            plan_row = connection.execute(
                "SELECT * FROM experimental_validation_plans WHERE project_id = ? ORDER BY id DESC LIMIT 1",
                (project_id,)
            ).fetchone()

        # 3. Experimental Feedback
        feedback_row = None
        if request.experimental_feedback_id:
            feedback_row = connection.execute(
                "SELECT * FROM prediction_feedback_summaries WHERE id = ?",
                (request.experimental_feedback_id,)
            ).fetchone()
        elif project_id:
            feedback_row = connection.execute(
                "SELECT * FROM prediction_feedback_summaries WHERE project_id = ? ORDER BY id DESC LIMIT 1",
                (project_id,)
            ).fetchone()

    # Extract prioritization run details
    scoring_profile = "balanced_admet"
    raw_candidates = []
    prioritization_warnings = []
    if run_row:
        scoring_profile = run_row["scoring_profile"]
        run_summary = _json_loads(run_row["summary_json"], {})
        raw_candidates = run_summary.get("ranked_candidates", [])
        prioritization_warnings = _json_loads(run_row["warnings_json"], [])

    # Deduplicate candidates using RDKit canonical SMILES or normalized name/ID fallback
    seen_keys = {}
    for c in raw_candidates:
        key = _get_dedup_key(c)
        if key not in seen_keys:
            seen_keys[key] = []
        seen_keys[key].append(c)
        
    ranked_candidates = []
    for key, duplicates in seen_keys.items():
        duplicates.sort(key=_candidate_quality_key, reverse=True)
        ranked_candidates.append(duplicates[0])
        
    ranked_candidates.sort(key=lambda x: (x.get("rank") if x.get("rank") is not None else 999999))
    for idx, c in enumerate(ranked_candidates):
        c["rank"] = idx + 1
        
    removed_count = len(raw_candidates) - len(ranked_candidates)

    # Extract validation plan details
    plan_title = None
    recommended_assays_list = []
    if plan_row:
        plan_title = plan_row["plan_title"]
        plan_summary = _json_loads(plan_row["summary_json"], {})
        candidate_plans = plan_summary.get("candidate_plans", [])
        for cp in candidate_plans:
            comp_name = cp.get("compound_name") or cp.get("compound_id")
            for assay in cp.get("recommended_assays", []):
                recommended_assays_list.append({
                    "compound_name": comp_name,
                    "assay_name": assay.get("assay_name"),
                    "recommendation_priority": assay.get("recommendation_priority"),
                    "rationale": assay.get("rationale")
                })

    # Group and limit top 10 recommended assays
    sorted_assays = []
    for assay in recommended_assays_list:
        clean_rat = _get_rationale(assay.get("rationale"))
        sorted_assays.append({
            "compound_name": assay.get("compound_name"),
            "assay_name": assay.get("assay_name"),
            "recommendation_priority": assay.get("recommendation_priority") or "recommended",
            "rationale": clean_rat,
            "category": _categorize_assay(assay.get("assay_name", ""))
        })
    sorted_assays.sort(key=lambda x: _priority_score(x["recommendation_priority"]), reverse=True)
    top_10_assays = sorted_assays[:10]
    
    grouped_top_assays = {}
    for assay in top_10_assays:
        cat = assay["category"]
        if cat not in grouped_top_assays:
            grouped_top_assays[cat] = []
        grouped_top_assays[cat].append(assay)

    # Clean rationale for full recommended assays list in JSON payload
    full_clean_assays = []
    for assay in recommended_assays_list:
        full_clean_assays.append({
            "compound_name": assay.get("compound_name"),
            "assay_name": assay.get("assay_name"),
            "recommendation_priority": assay.get("recommendation_priority") or "recommended",
            "rationale": _get_rationale(assay.get("rationale"))
        })

    # Extract experimental feedback details
    agreement_summary = {}
    candidate_feedback_list = []
    if feedback_row:
        agreement_summary = _json_loads(feedback_row["agreement_summary_json"], {})
        feedback_summary = _json_loads(feedback_row["feedback_summary_json"], {})
        candidate_feedback_list = feedback_summary.get("candidate_feedback", [])

    # Target handling and warnings
    user_disease = request.disease_name or disease_area or "breast cancer"
    user_target = request.user_entered_target or target_name or "EGFR"
    resolved_target = request.resolved_target or target_name or "EGFR"
    
    if user_target.strip().lower() != resolved_target.strip().lower():
        warning_msg = "Resolved target differs from user-entered target. Please verify target selection before interpretation."
        if warning_msg not in prioritization_warnings:
            prioritization_warnings.append(warning_msg)

    # Compile Executive Summary findings paragraph
    findings_str = (
        f"This concise Disease-to-Lead report details computational decision-support analysis for disease area '{user_disease}' "
        f"and user-entered target '{user_target}'. Target query resolved to '{resolved_target}'."
    )
    if user_target.strip().lower() != resolved_target.strip().lower():
        findings_str += f" WARNING: Resolved target '{resolved_target}' differs from user-entered target '{user_target}'. Please verify target selection before interpretation."
        
    if request.known_compound:
        findings_str += f" The known reference compound '{request.known_compound}' was included for workflow calibration."
        
    findings_str += f" After deduplicating candidates using RDKit (removing {removed_count} duplicate record(s)), a total of {len(ranked_candidates)} unique compound(s) were analyzed."
    
    if ranked_candidates:
        top_cand = ranked_candidates[0]
        findings_str += f" The top prioritization candidate is '{top_cand.get('compound_name') or top_cand.get('compound_id')}' with a total score of {top_cand.get('total_score'):.2f}."
        
        missing = top_cand.get("missing_evidence") or []
        if missing:
            findings_str += f" The primary missing evidence for the top candidate includes: {', '.join(missing)}."
        else:
            findings_str += " The top candidate has complete model and rule-based evidence."
            
        next_step = top_cand.get("recommended_next_validation_step") or "Recommended to reduce key uncertainty before experimental follow-up."
        findings_str += f" The recommended next step is: {next_step}"
    else:
        findings_str += " No candidates were prioritized."

    # Active trained model details
    active_model = get_active_trained_model_info()
    has_active_model = active_model and active_model.get("status") not in ("unavailable", "disabled", "error")

    # External Validation runs
    ext_runs = []
    if has_active_model and active_model.get("model_id"):
        with get_connection() as connection:
            ext_rows = connection.execute(
                "SELECT * FROM admet_external_validation_runs WHERE model_id = ? ORDER BY id DESC LIMIT 5",
                (active_model["model_id"],)
            ).fetchall()
            for r in ext_rows:
                ext_runs.append({
                    "id": r["id"],
                    "model_id": r["model_id"],
                    "task_name": r["task_name"],
                    "task_type": r["task_type"],
                    "status": r["status"],
                    "metric_summary": _json_loads(r["metric_summary_json"], {})
                })

    # Recommended next steps
    next_steps = [
        "Confirm target relevance by verifying EGFR binding selectivity profiles.",
        "Perform identity and structural purity verification for top priority candidates.",
        "Design and execute basic in vitro ADMET assays to validate computational predictions.",
        "Run specific bioassays targeting EGFR to establish cellular efficacy metrics.",
        "Integrate experimental results back into the DrugScreen360 active learning loop."
    ]

    # Limitations
    limitations = [
        "Computational predictions are statistical in nature and do not guarantee safety or efficacy.",
        "Missing experimental assay data reduces confidence in overall project outcomes.",
        "ADMET and developability risks should be validated experimentally using recommended assays.",
        "This decision support report should be reviewed by qualified scientific personnel."
    ]

    included_sections = ["screening", "admet_prediction"]
    if run_row:
        included_sections.append("lead_prioritization")
    if plan_row:
        included_sections.append("validation_planner")
    if feedback_row:
        included_sections.append("experimental_feedback")

    missing_sections = []
    if not run_row:
        missing_sections.append("lead_prioritization")
    if not plan_row:
        missing_sections.append("validation_planner")
    if not feedback_row:
        missing_sections.append("experimental_feedback")

    executive_summary = {
        "project_name": project_title,
        "generated_at": created_at,
        "molecule_or_candidate_count": len(ranked_candidates),
        "top_candidates": [
            {
                "compound_name": c.get("compound_name"),
                "total_score": c.get("total_score"),
                "priority_label": c.get("priority_label")
            }
            for c in ranked_candidates[:5]
        ],
        "main_findings": [findings_str],
        "main_warnings": list(dict.fromkeys(prioritization_warnings)),
        "next_recommended_steps": next_steps
    }

    return {
        "report_title": request.report_title,
        "scientific_notice": SCIENTIFIC_NOTICE,
        "is_concise_mode": True,
        "project_title": project_title,
        "disease_area": disease_area,
        "target_name": target_name,
        "scoring_profile": scoring_profile,
        "created_at": created_at,
        "app_version": app_version(),
        "included_sections": included_sections,
        "missing_sections": missing_sections,
        "warnings": prioritization_warnings,
        "executive_summary": executive_summary,
        
        # Section 1: Executive Summary
        "executive_summary_paragraph": findings_str,
        
        # Section 2: Workflow Input Table
        "workflow_input_table": {
            "target_name": resolved_target,
            "user_entered_target": user_target,
            "resolved_target": resolved_target,
            "disease_area": disease_area,
            "scoring_profile": scoring_profile,
            "candidate_count": len(ranked_candidates)
        },
        
        # Section 3: Workflow Completion Table
        "workflow_completion": {
            "screening": "Completed",
            "admet_prediction": "Completed",
            "lead_prioritization": "Completed" if run_row else "Pending",
            "validation_planning": "Completed" if plan_row else "Skipped/Not Run",
            "experimental_feedback": "Completed" if feedback_row else "Skipped/Not Run"
        },
        
        # Section 4: Top Candidate Table
        "top_candidate_table": [
            {
                "rank": idx + 1,
                "compound_name": c.get("compound_name") or c.get("compound_id") or "Unnamed",
                "compound_id": c.get("compound_id") or "N/A",
                "smiles": c.get("smiles") or "N/A",
                "total_score": c.get("total_score") or 0.0,
                "priority_label": c.get("priority_label") or "N/A"
            }
            for idx, c in enumerate(ranked_candidates[:5])
        ],
        
        # Section 5: Top Candidate Interpretation
        "top_candidate_interpretation": [
            {
                "compound_name": c.get("compound_name") or "Unnamed",
                "priority_label": c.get("priority_label") or "N/A",
                "ranking_explanation": _generate_candidate_explanation(c, scoring_profile),
                "positive_factors": c.get("positive_factors") or [],
                "risk_factors": c.get("risk_factors") or [],
                "recommended_next_step": _get_rationale(c.get("recommended_next_validation_step"))
            }
            for c in ranked_candidates[:5]
        ],
        
        # Section 6: ADMET & Drug-likeness Summary
        "admet_drug_likeness": [
            {
                "compound_name": c.get("compound_name") or "Unnamed",
                "descriptors": c.get("descriptors") or {},
                "lipinski_status": c.get("lipinski_status") or "not evaluated",
                "veber_status": c.get("veber_status") or "not evaluated",
                "drug_likeness_status": c.get("drug_likeness_status") or "not evaluated",
                "developability_risk": c.get("developability_risk") or "not evaluated",
                "rule_based_admet_summary": c.get("rule_based_admet_summary") or {},
                "missing_evidence": c.get("missing_evidence") or []
            }
            for c in ranked_candidates[:5]
        ],
        
        # Section 7: Model Evidence Summary
        "has_active_model": has_active_model,
        "model_evidence": {
            "model_id": active_model.get("model_id") if has_active_model else None,
            "model_type": active_model.get("model_type") if has_active_model else None,
            "task_type": active_model.get("task_type") if has_active_model else None,
            "status": active_model.get("status") if has_active_model else "unavailable"
        },
        
        # Section 8: External Validation Summary
        "external_validation": {
            "has_external_validation": len(ext_runs) > 0,
            "validation_details": ext_runs
        },
        
        # Section 9: Experimental Feedback Summary
        "experimental_feedback": {
            "has_feedback": bool(feedback_row),
            "supported_count": agreement_summary.get("supported_count", 0) if feedback_row else 0,
            "contradicted_count": agreement_summary.get("contradicted_count", 0) if feedback_row else 0,
            "inconclusive_count": agreement_summary.get("inconclusive_count", 0) if feedback_row else 0,
            "not_comparable_count": agreement_summary.get("not_comparable_count", 0) if feedback_row else 0,
            "candidate_feedback": [
                {
                    "compound_name": cf.get("compound_name") or "Unnamed",
                    "assay_name": cf.get("assay_name") or "N/A",
                    "measured_value": cf.get("measured_value") or "N/A",
                    "feedback_label": cf.get("feedback_label") or "N/A",
                    "explanation": cf.get("explanation") or ""
                }
                for cf in candidate_feedback_list
            ]
        },
        
        # Section 10: Validation Planner Summary
        "validation_planner": {
            "has_plan": bool(plan_row),
            "plan_title": plan_title,
            "recommended_assays": full_clean_assays,
            "grouped_top_assays": grouped_top_assays
        },
        
        # Section 11: Limitations
        "limitations": limitations,
        
        # Section 12: Recommended Next Steps
        "recommended_next_steps": next_steps,
        
        # Section 13: Reproducibility
        "reproducibility": {
            "app_version": app_version(),
            "python_version": sys.version.split()[0],
            "platform": platform.platform(),
            "generated_at": created_at
        }
    }


def _build_payload(request: FinalProjectReportRequest, created_at: str) -> dict[str, Any]:
    if request.report_mode == "concise_disease_to_lead_report":
        return _build_payload_concise(request, created_at)
        
    context = _project_context(request.project_id)
    sections = [
        _screening_section(request),
        _training_section(request),
        _prediction_section(request),
        _external_validation_section(request),
        _domain_section(request),
        _explainability_section(request),
        _lead_section(request),
        _validation_planner_section(request),
        _experimental_feedback_section(request),
    ]
    included = [section.section_id for section in sections if section.included]
    missing = [section.section_id for section in sections if not section.included and section.summary.get("status") != "not requested"]
    warnings = list(context.get("warnings") or [])
    project_items = ((context.get("project") or {}).get("items") or []) if isinstance(context.get("project"), dict) else []
    if any((item.get("metadata") or {}).get("demo_mode") or (item.get("metadata") or {}).get("data_source") == "demo" or "demo" in str(item.get("item_type", "")) for item in project_items):
        warnings.append("Demo data for software demonstration only. Not experimental or clinical evidence.")
    for section in sections:
        warnings.extend(section.warnings)
    screening_count = next((section.summary.get("screening_run_count", 0) for section in sections if section.section_id == "screening"), 0)
    lead_top = next((section.summary.get("top_candidates", []) for section in sections if section.section_id == "lead_prioritization"), [])
    dashboard = context.get("dashboard") or {}
    next_steps = list(dashboard.get("recommended_next_steps") or [])
    if not next_steps:
        next_steps = [
            "Complete missing data before relying on computational summaries.",
            "Run or review experimental validation assays for candidates kept under consideration.",
            "Use model retraining only when enough curated and validated experimental data exists.",
        ]
    summary = FinalProjectReportSummary(
        project_name=(context.get("project") or {}).get("title") if context.get("project") else None,
        generated_at=created_at,
        molecule_or_candidate_count=int(screening_count or len(dashboard.get("candidate_matrix") or [])),
        top_candidates=lead_top[:5],
        main_findings=[
            f"Included sections: {', '.join(included) or 'none'}",
            f"Missing sections: {', '.join(missing)}" if missing else "All sections are present",
        ],
        main_warnings=list(dict.fromkeys(warnings))[:20],
        next_recommended_steps=next_steps,
    )
    return {
        "report_title": request.report_title,
        "project_id": request.project_id,
        "created_at": created_at,
        "app_version": app_version(),
        "scientific_notice": SCIENTIFIC_NOTICE,
        "executive_summary": summary.model_dump(),
        "project_context": context,
        "sections": [section.model_dump() for section in sections],
        "included_sections": included,
        "missing_sections": missing,
        "final_limitations": FINAL_LIMITATIONS,
        "reproducibility": {
            "app_version": app_version(),
            "python_version": sys.version.split()[0],
            "python_implementation": platform.python_implementation(),
            "run_command": ".\\scripts\\start_all.ps1",
            "test_command": ".\\scripts\\run_tests.ps1",
            "generated_at": created_at,
        },
        "warnings": list(dict.fromkeys(warnings)),
    }


def _pdf_table(rows: list[list[str]], widths: list[float] | None = None) -> Table:
    table = Table(rows, colWidths=widths or [2.0 * inch, 4.6 * inch], repeatRows=1 if len(rows) > 1 else 0)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef2f5")),
                ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#c8d1dc")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("FONTSIZE", (0, 0), (-1, -1), 7.2),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    return table


def _build_pdf_table(headers: list[str], rows: list[list[str]], widths: list[float] | None = None) -> Table:
    styles = getSampleStyleSheet()
    cell_style = styles["Normal"]
    cell_style.fontSize = 8
    cell_style.leading = 10
    
    header_style = styles["Normal"]
    header_style.fontSize = 8
    header_style.leading = 10
    header_style.textColor = colors.HexColor("#1b365d")
    
    data = []
    data.append([Paragraph(f"<b>{h}</b>", header_style) for h in headers])
    for r in rows:
        data.append([Paragraph(str(cell), cell_style) for cell in r])
        
    table = Table(data, colWidths=widths, repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
                ("TOPPADDING", (0, 0), (-1, 0), 6),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 1), (-1, -1), 4),
                ("TOPPADDING", (0, 1), (-1, -1), 4),
            ]
        )
    )
    return table


def _build_docx_table(doc, headers: list[str], rows: list[list[str]]):
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"
    hdr_cells = table.rows[0].cells
    for i, title in enumerate(headers):
        hdr_cells[i].text = title
    for row_data in rows:
        row_cells = table.add_row().cells
        for i, val in enumerate(row_data):
            row_cells[i].text = str(val)
    return table


def _pairs(mapping: dict[str, Any]) -> list[list[str]]:
    return [["Field", "Value"], *[[key.replace("_", " ").title(), _safe(value)] for key, value in mapping.items()]]


def _build_pdf(payload: dict[str, Any]) -> bytes:
    buffer = BytesIO()
    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=0.45 * inch, leftMargin=0.45 * inch)
    
    if payload.get("is_concise_mode"):
        story = []
        story.append(Paragraph(f"<font size=16 color=#1b365d><b>{payload['report_title']}</b></font>", styles["Title"]))
        story.append(Spacer(1, 10))
        story.append(Paragraph(f"<i>Notice: {payload['scientific_notice']}</i>", styles["Normal"]))
        story.append(Spacer(1, 15))
        
        # 1. Executive Summary
        story.append(Paragraph("<b>Executive Summary</b>", styles["Heading2"]))
        story.append(Spacer(1, 5))
        story.append(Paragraph(payload["executive_summary_paragraph"], styles["BodyText"]))
        story.append(Spacer(1, 15))
        
        # 2. Workflow Input Table
        story.append(Paragraph("<b>Workflow Input Table</b>", styles["Heading2"]))
        story.append(Spacer(1, 5))
        inputs = payload["workflow_input_table"]
        input_rows = [
            ["User-entered Target", inputs.get("user_entered_target") or "not available"],
            ["Resolved Target", inputs.get("resolved_target") or "not available"],
            ["Disease Area", inputs["disease_area"]],
            ["Scoring Profile", inputs["scoring_profile"]],
            ["Candidate Count", str(inputs["candidate_count"])]
        ]
        story.append(_build_pdf_table(["Input Parameter", "Value"], input_rows, widths=[2.5*inch, 4.5*inch]))
        story.append(Spacer(1, 15))
        
        if inputs.get("user_entered_target") != inputs.get("resolved_target"):
            story.append(Paragraph("<b>WARNING: Resolved target differs from user-entered target. Please verify target selection before interpretation.</b>", styles["Normal"]))
            story.append(Spacer(1, 10))

        # 3. Workflow Completion Table
        story.append(Paragraph("<b>Workflow Completion Table</b>", styles["Heading2"]))
        story.append(Spacer(1, 5))
        completion = payload["workflow_completion"]
        completion_rows = [
            ["Step 1: Candidate Discovery", completion["screening"]],
            ["Step 2: ADMET Prediction", completion["admet_prediction"]],
            ["Step 3: Lead Prioritization & Scoring", completion["lead_prioritization"]],
            ["Step 4: Validation Planning", completion["validation_planning"]],
            ["Step 5: Experimental Feedback Analysis", completion["experimental_feedback"]]
        ]
        story.append(_build_pdf_table(["Workflow Step", "Status"], completion_rows, widths=[3.5*inch, 3.5*inch]))
        story.append(Spacer(1, 15))
        
        # 4. Top Candidate Table
        story.append(Paragraph("<b>Top Candidate Table</b>", styles["Heading2"]))
        story.append(Spacer(1, 5))
        top_candidates = payload["top_candidate_table"]
        if top_candidates:
            headers = ["Rank", "Compound Name", "Compound ID", "SMILES", "Total Score", "Priority Label"]
            rows = []
            for c in top_candidates:
                smiles_disp = c["smiles"]
                if len(smiles_disp) > 30:
                    smiles_disp = smiles_disp[:27] + "..."
                rows.append([
                    str(c["rank"]),
                    c["compound_name"],
                    c["compound_id"],
                    smiles_disp,
                    f"{c['total_score']:.2f}",
                    c["priority_label"].replace("_", " ").title()
                ])
            story.append(_build_pdf_table(headers, rows, widths=[0.5*inch, 1.3*inch, 1.2*inch, 2.0*inch, 0.8*inch, 1.2*inch]))
            story.append(Spacer(1, 5))
            story.append(Paragraph("<i>Note: Duplicate candidate records were merged based on canonical SMILES or compound identity.</i>", styles["Normal"]))
        else:
            story.append(Paragraph("No candidates evaluated.", styles["BodyText"]))
        story.append(Spacer(1, 15))
        
        # 5. Top Candidate Interpretation
        story.append(Paragraph("<b>Top Candidate Interpretation</b>", styles["Heading2"]))
        story.append(Spacer(1, 5))
        interpretations = payload["top_candidate_interpretation"]
        if interpretations:
            for idx, c in enumerate(interpretations):
                story.append(Paragraph(f"<b>Candidate {idx+1}: {c['compound_name']} (Priority: {c['priority_label'].replace('_', ' ').title()})</b>", styles["Normal"]))
                story.append(Spacer(1, 2))
                story.append(Paragraph(f"<u>Explanation</u>: {c['ranking_explanation']}", styles["BodyText"]))
                if c["positive_factors"]:
                    story.append(Paragraph(f"<u>Positive Factors</u>: {', '.join(c['positive_factors'])}", styles["BodyText"]))
                if c["risk_factors"]:
                    story.append(Paragraph(f"<u>Risk Factors</u>: {', '.join(c['risk_factors'])}", styles["BodyText"]))
                story.append(Paragraph(f"<u>Recommended Next Step</u>: {c['recommended_next_step']}", styles["BodyText"]))
                story.append(Spacer(1, 8))
        else:
            story.append(Paragraph("No candidate interpretations available.", styles["BodyText"]))
        story.append(Spacer(1, 15))
        
        # 6. ADMET & Drug-likeness Summary
        story.append(Paragraph("<b>ADMET & Drug-likeness Summary</b>", styles["Heading2"]))
        story.append(Spacer(1, 5))
        admet_list = payload["admet_drug_likeness"]
        if admet_list:
            headers = ["Compound", "MW", "LogP", "TPSA", "HBD", "HBA", "RotB", "Lipinski", "Veber", "Concern Lvl", "Score", "Warning/Missing Evidence"]
            rows = []
            for a in admet_list:
                desc = a.get("descriptors") or {}
                rules = a.get("rule_based_admet_summary") or {}
                missing = a.get("missing_evidence") or []
                main_warning = ", ".join(missing) if missing else "None"
                if len(main_warning) > 30:
                    main_warning = main_warning[:27] + "..."
                rows.append([
                    a["compound_name"],
                    f"{desc.get('molecular_weight', 'N/A')}",
                    f"{desc.get('logp', 'N/A')}",
                    f"{desc.get('tpsa', 'N/A')}",
                    f"{desc.get('hydrogen_bond_donors', 'N/A')}",
                    f"{desc.get('hydrogen_bond_acceptors', 'N/A')}",
                    f"{desc.get('rotatable_bonds', 'N/A')}",
                    a["lipinski_status"].title(),
                    a["veber_status"].title(),
                    rules.get("concern_level", "N/A").replace("_", " ").title(),
                    f"{rules.get('concern_score', 'N/A')}",
                    main_warning
                ])
            story.append(_build_pdf_table(headers, rows, widths=[0.9*inch, 0.5*inch, 0.4*inch, 0.45*inch, 0.35*inch, 0.35*inch, 0.4*inch, 0.7*inch, 0.6*inch, 0.8*inch, 0.5*inch, 1.65*inch]))
        else:
            story.append(Paragraph("No ADMET evaluations available.", styles["BodyText"]))
        story.append(Spacer(1, 15))
        
        # 7. Model Evidence Summary
        story.append(Paragraph("<b>Model Evidence Summary</b>", styles["Heading2"]))
        story.append(Spacer(1, 5))
        if payload["has_active_model"]:
            m = payload["model_evidence"]
            m_rows = [
                ["Active Model ID", m["model_id"] or "N/A"],
                ["Model Type", m["model_type"] or "N/A"],
                ["Task Type", m["task_type"] or "N/A"],
                ["Status", m["status"].title() if m["status"] else "N/A"]
            ]
            story.append(_build_pdf_table(["Property", "Value"], m_rows, widths=[2.5*inch, 4.5*inch]))
        else:
            story.append(Paragraph("No active trained ADMET model was available. This report used descriptor-based and rule-based evidence only.", styles["BodyText"]))
        story.append(Spacer(1, 15))
        
        # 8. External Validation Summary
        story.append(Paragraph("<b>External Validation Summary</b>", styles["Heading2"]))
        story.append(Spacer(1, 5))
        ext_val = payload["external_validation"]
        if ext_val["has_external_validation"]:
            headers = ["Task Name", "Task Type", "Status", "Accuracy / AUC"]
            rows = []
            for r in ext_val["validation_details"]:
                metrics = r["metric_summary"]
                metric_str = ", ".join(f"{k}: {v}" for k, v in metrics.items() if not isinstance(v, (dict, list)))
                rows.append([
                    r["task_name"] or "N/A",
                    r["task_type"],
                    r["status"].title(),
                    metric_str or "N/A"
                ])
            story.append(_build_pdf_table(headers, rows, widths=[2.0*inch, 1.5*inch, 1.2*inch, 2.3*inch]))
        else:
            story.append(Paragraph("External validation/calibration was not available for this project.", styles["BodyText"]))
        story.append(Spacer(1, 15))
        
        # 9. Experimental Feedback Summary
        story.append(Paragraph("<b>Experimental Feedback Summary</b>", styles["Heading2"]))
        story.append(Spacer(1, 5))
        fb = payload["experimental_feedback"]
        if fb["has_feedback"]:
            story.append(Paragraph(
                f"Agreement Metrics: Supported predictions ({fb['supported_count']}), "
                f"Contradicted predictions ({fb['contradicted_count']}), "
                f"Inconclusive ({fb['inconclusive_count']}), "
                f"Not Comparable ({fb['not_comparable_count']}).",
                styles["BodyText"]
            ))
            story.append(Spacer(1, 5))
            if fb["candidate_feedback"]:
                headers = ["Compound Name", "Assay Name", "Measured Value", "Feedback Label", "Explanation"]
                rows = [
                    [
                        f["compound_name"],
                        f["assay_name"],
                        f["measured_value"],
                        f["feedback_label"].replace("_", " ").title(),
                        f["explanation"]
                    ]
                    for f in fb["candidate_feedback"]
                ]
                story.append(_build_pdf_table(headers, rows, widths=[1.2*inch, 1.3*inch, 1.0*inch, 1.5*inch, 2.0*inch]))
        else:
            story.append(Paragraph("No user-entered experimental assay results were imported. Experimental feedback comparison was not performed.", styles["BodyText"]))
        story.append(Spacer(1, 15))
        
        # 10. Validation Planner Summary
        story.append(Paragraph("<b>Validation Planner Summary</b>", styles["Heading2"]))
        story.append(Spacer(1, 5))
        vp = payload["validation_planner"]
        if vp["has_plan"]:
            story.append(Paragraph(f"Plan Title: {vp['plan_title'] or 'N/A'}", styles["Normal"]))
            story.append(Spacer(1, 5))
            
            # Show only top 10 grouped recommendations
            grouped = vp.get("grouped_top_assays") or {}
            if grouped:
                for category, assays in grouped.items():
                    story.append(Paragraph(f"<b>Category: {category}</b>", styles["Normal"]))
                    story.append(Spacer(1, 2))
                    headers = ["Compound Name", "Assay Name", "Priority", "Rationale"]
                    rows = []
                    for a in assays:
                        rows.append([
                            a["compound_name"],
                            a["assay_name"],
                            a["recommendation_priority"].title(),
                            a["rationale"]
                        ])
                    story.append(_build_pdf_table(headers, rows, widths=[1.5*inch, 1.5*inch, 1.0*inch, 3.0*inch]))
                    story.append(Spacer(1, 5))
            else:
                story.append(Paragraph("No validation planner recommendations available.", styles["BodyText"]))
        else:
            story.append(Paragraph("No validation plan was generated for this project.", styles["BodyText"]))
        story.append(Spacer(1, 15))
        
        # 11. Limitations
        story.append(Paragraph("<b>Limitations</b>", styles["Heading2"]))
        story.append(Spacer(1, 5))
        for lim in payload["limitations"]:
            story.append(Paragraph(f"- {lim}", styles["BodyText"]))
        story.append(Spacer(1, 15))
        
        # 12. Recommended Next Steps
        story.append(Paragraph("<b>Recommended Next Steps</b>", styles["Heading2"]))
        story.append(Spacer(1, 5))
        for step in payload["recommended_next_steps"]:
            story.append(Paragraph(f"- {step}", styles["BodyText"]))
        story.append(Spacer(1, 15))
        
        # 13. Reproducibility
        story.append(Paragraph("<b>Reproducibility</b>", styles["Heading2"]))
        story.append(Spacer(1, 5))
        rep = payload["reproducibility"]
        rep_rows = [
            ["App Version", rep["app_version"]],
            ["Python Version", rep["python_version"]],
            ["Platform", rep["platform"]],
            ["Generated At", rep["generated_at"]]
        ]
        story.append(_build_pdf_table(["Reproducibility Parameter", "Value"], rep_rows, widths=[2.5*inch, 4.5*inch]))
        
        doc.build(story)
        return buffer.getvalue()

    story = [Paragraph(payload["report_title"], styles["Title"]), Paragraph(payload["scientific_notice"], styles["BodyText"]), Spacer(1, 10)]
    story.append(Paragraph("Executive Summary", styles["Heading2"]))
    story.append(_pdf_table(_pairs(payload["executive_summary"])))
    for section in payload["sections"]:
        story.append(Paragraph(section["title"], styles["Heading2"]))
        if section["included"]:
            story.append(_pdf_table(_pairs(section.get("summary") or {})))
            story.append(Paragraph(f"Number of records: {len(section.get('records') or [])}", styles["BodyText"]))
        else:
            story.append(Paragraph("No stored data available for this section, or the section was not requested.", styles["BodyText"]))
        for warning in section.get("warnings") or []:
            story.append(Paragraph(f"- {warning}", styles["BodyText"]))
    story.append(Paragraph("Final Limitations", styles["Heading2"]))
    for item in payload["final_limitations"]:
        story.append(Paragraph(f"- {item}", styles["BodyText"]))
    story.append(Paragraph("Recommended Next Steps", styles["Heading2"]))
    for item in payload["executive_summary"].get("next_recommended_steps") or []:
        story.append(Paragraph(f"- {item}", styles["BodyText"]))
    story.append(Paragraph("Reproducibility", styles["Heading2"]))
    story.append(_pdf_table(_pairs(payload["reproducibility"])))
    doc.build(story)
    return buffer.getvalue()


def _build_docx(payload: dict[str, Any]) -> bytes:
    document = Document()
    
    if payload.get("is_concise_mode"):
        document.add_heading(payload["report_title"], 0)
        document.add_paragraph(f"Notice: {payload['scientific_notice']}")
        
        # 1. Executive Summary
        document.add_heading("Executive Summary", level=1)
        document.add_paragraph(payload["executive_summary_paragraph"])
        
        # 2. Workflow Input Table
        document.add_heading("Workflow Input Table", level=1)
        inputs = payload["workflow_input_table"]
        _build_docx_table(document, ["Input Parameter", "Value"], [
            ["User-entered Target", inputs.get("user_entered_target") or "not available"],
            ["Resolved Target", inputs.get("resolved_target") or "not available"],
            ["Disease Area", inputs["disease_area"]],
            ["Scoring Profile", inputs["scoring_profile"]],
            ["Candidate Count", str(inputs["candidate_count"])]
        ])
        
        if inputs.get("user_entered_target") != inputs.get("resolved_target"):
            p = document.add_paragraph()
            p.add_run("WARNING: Resolved target differs from user-entered target. Please verify target selection before interpretation.").bold = True
            
        # 3. Workflow Completion Table
        document.add_heading("Workflow Completion Table", level=1)
        completion = payload["workflow_completion"]
        _build_docx_table(document, ["Workflow Step", "Status"], [
            ["Step 1: Candidate Discovery", completion["screening"]],
            ["Step 2: ADMET Prediction", completion["admet_prediction"]],
            ["Step 3: Lead Prioritization & Scoring", completion["lead_prioritization"]],
            ["Step 4: Validation Planning", completion["validation_planning"]],
            ["Step 5: Experimental Feedback Analysis", completion["experimental_feedback"]]
        ])
        
        # 4. Top Candidate Table
        document.add_heading("Top Candidate Table", level=1)
        top_candidates = payload["top_candidate_table"]
        if top_candidates:
            rows = []
            for c in top_candidates:
                rows.append([
                    str(c["rank"]),
                    c["compound_name"],
                    c["compound_id"],
                    c["smiles"],
                    f"{c['total_score']:.2f}",
                    c["priority_label"].replace("_", " ").title()
                ])
            _build_docx_table(document, ["Rank", "Compound Name", "Compound ID", "SMILES", "Total Score", "Priority Label"], rows)
            document.add_paragraph("Duplicate candidate records were merged based on canonical SMILES or compound identity.", style="Normal")
        else:
            document.add_paragraph("No candidates evaluated.")
            
        # 5. Top Candidate Interpretation
        document.add_heading("Top Candidate Interpretation", level=1)
        interpretations = payload["top_candidate_interpretation"]
        if interpretations:
            for idx, c in enumerate(interpretations):
                document.add_heading(f"Candidate {idx+1}: {c['compound_name']} (Priority: {c['priority_label'].replace('_', ' ').title()})", level=2)
                document.add_paragraph(f"Explanation: {c['ranking_explanation']}")
                if c["positive_factors"]:
                    document.add_paragraph(f"Positive Factors: {', '.join(c['positive_factors'])}")
                if c["risk_factors"]:
                    document.add_paragraph(f"Risk Factors: {', '.join(c['risk_factors'])}")
                document.add_paragraph(f"Recommended Next Step: {c['recommended_next_step']}")
        else:
            document.add_paragraph("No candidate interpretations available.")
            
        # 6. ADMET & Drug-likeness Summary
        document.add_heading("ADMET & Drug-likeness Summary", level=1)
        admet_list = payload["admet_drug_likeness"]
        if admet_list:
            headers = ["Compound", "MW", "LogP", "TPSA", "HBD", "HBA", "RotB", "Lipinski", "Veber", "Concern Lvl", "Score", "Warning/Missing Evidence"]
            rows = []
            for a in admet_list:
                desc = a.get("descriptors") or {}
                rules = a.get("rule_based_admet_summary") or {}
                missing = a.get("missing_evidence") or []
                main_warning = ", ".join(missing) if missing else "None"
                rows.append([
                    a["compound_name"],
                    f"{desc.get('molecular_weight', 'N/A')}",
                    f"{desc.get('logp', 'N/A')}",
                    f"{desc.get('tpsa', 'N/A')}",
                    f"{desc.get('hydrogen_bond_donors', 'N/A')}",
                    f"{desc.get('hydrogen_bond_acceptors', 'N/A')}",
                    f"{desc.get('rotatable_bonds', 'N/A')}",
                    a["lipinski_status"].title(),
                    a["veber_status"].title(),
                    rules.get("concern_level", "N/A").replace("_", " ").title(),
                    f"{rules.get('concern_score', 'N/A')}",
                    main_warning
                ])
            _build_docx_table(document, headers, rows)
        else:
            document.add_paragraph("No ADMET evaluations available.")
            
        # 7. Model Evidence Summary
        document.add_heading("Model Evidence Summary", level=1)
        if payload["has_active_model"]:
            m = payload["model_evidence"]
            _build_docx_table(document, ["Property", "Value"], [
                ["Active Model ID", m["model_id"] or "N/A"],
                ["Model Type", m["model_type"] or "N/A"],
                ["Task Type", m["task_type"] or "N/A"],
                ["Status", m["status"].title() if m["status"] else "N/A"]
            ])
        else:
            document.add_paragraph("No active trained ADMET model was available. This report used descriptor-based and rule-based evidence only.")
            
        # 8. External Validation Summary
        document.add_heading("External Validation Summary", level=1)
        ext_val = payload["external_validation"]
        if ext_val["has_external_validation"]:
            rows = []
            for r in ext_val["validation_details"]:
                metrics = r["metric_summary"]
                metric_str = ", ".join(f"{k}: {v}" for k, v in metrics.items() if not isinstance(v, (dict, list)))
                rows.append([
                    r["task_name"] or "N/A",
                    r["task_type"],
                    r["status"].title(),
                    metric_str or "N/A"
                ])
            _build_docx_table(document, ["Task Name", "Task Type", "Status", "Accuracy / AUC"], rows)
        else:
            document.add_paragraph("External validation/calibration was not available for this project.")
            
        # 9. Experimental Feedback Summary
        document.add_heading("Experimental Feedback Summary", level=1)
        fb = payload["experimental_feedback"]
        if fb["has_feedback"]:
            document.add_paragraph(
                f"Agreement Metrics: Supported predictions ({fb['supported_count']}), "
                f"Contradicted predictions ({fb['contradicted_count']}), "
                f"Inconclusive ({fb['inconclusive_count']}), "
                f"Not Comparable ({fb['not_comparable_count']})."
            )
            if fb["candidate_feedback"]:
                rows = [
                    [
                        f["compound_name"],
                        f["assay_name"],
                        f["measured_value"],
                        f["feedback_label"].replace("_", " ").title(),
                        f["explanation"]
                    ]
                    for f in fb["candidate_feedback"]
                ]
                _build_docx_table(document, ["Compound Name", "Assay Name", "Measured Value", "Feedback Label", "Explanation"], rows)
        else:
            document.add_paragraph("No user-entered experimental assay results were imported. Experimental feedback comparison was not performed.")
            
        # 10. Validation Planner Summary
        document.add_heading("Validation Planner Summary", level=1)
        vp = payload["validation_planner"]
        if vp["has_plan"]:
            document.add_paragraph(f"Plan Title: {vp['plan_title'] or 'N/A'}")
            
            # Show only top 10 grouped recommendations
            grouped = vp.get("grouped_top_assays") or {}
            if grouped:
                for category, assays in grouped.items():
                    document.add_heading(f"Category: {category}", level=2)
                    rows = []
                    for a in assays:
                        rows.append([
                            a["compound_name"],
                            a["assay_name"],
                            a["recommendation_priority"].title(),
                            a["rationale"]
                        ])
                    _build_docx_table(document, ["Compound Name", "Assay Name", "Priority", "Rationale"], rows)
            else:
                document.add_paragraph("No validation planner recommendations available.")
        else:
            document.add_paragraph("No validation plan was generated for this project.")
            
        # 11. Limitations
        document.add_heading("Limitations", level=1)
        for lim in payload["limitations"]:
            document.add_paragraph(lim, style="List Bullet")
            
        # 12. Recommended Next Steps
        document.add_heading("Recommended Next Steps", level=1)
        for step in payload["recommended_next_steps"]:
            document.add_paragraph(step, style="List Bullet")
            
        # 13. Reproducibility
        document.add_heading("Reproducibility", level=1)
        rep = payload["reproducibility"]
        _build_docx_table(document, ["Reproducibility Parameter", "Value"], [
            ["App Version", rep["app_version"]],
            ["Python Version", rep["python_version"]],
            ["Platform", rep["platform"]],
            ["Generated At", rep["generated_at"]]
        ])
        
        buffer = BytesIO()
        document.save(buffer)
        return buffer.getvalue()

    document.add_heading(payload["report_title"], 0)
    document.add_paragraph(payload["scientific_notice"])
    document.add_heading("Executive Summary", level=1)
    for key, value in payload["executive_summary"].items():
        document.add_paragraph(f"{key.replace('_', ' ').title()}: {_safe(value)}")
    for section in payload["sections"]:
        document.add_heading(section["title"], level=1)
        if section["included"]:
            for key, value in (section.get("summary") or {}).items():
                document.add_paragraph(f"{key.replace('_', ' ').title()}: {_safe(value)}")
            document.add_paragraph(f"Number of records: {len(section.get('records') or [])}")
        else:
            document.add_paragraph("No stored data available for this section, or the section was not requested.")
        for warning in section.get("warnings") or []:
            document.add_paragraph(warning, style="List Bullet")
    document.add_heading("Final Limitations", level=1)
    for item in payload["final_limitations"]:
        document.add_paragraph(item, style="List Bullet")
    document.add_heading("Recommended Next Steps", level=1)
    for item in payload["executive_summary"].get("next_recommended_steps") or []:
        document.add_paragraph(item, style="List Bullet")
    document.add_heading("Reproducibility", level=1)
    for key, value in payload["reproducibility"].items():
        document.add_paragraph(f"{key.replace('_', ' ').title()}: {_safe(value)}")
    buffer = BytesIO()
    document.save(buffer)
    return buffer.getvalue()


def _save_report(request: FinalProjectReportRequest, payload: dict[str, Any], files: dict[str, str]) -> int:
    init_db()
    with get_connection() as connection:
        cursor = connection.execute(
            """
            INSERT INTO final_project_reports (
                project_id, report_title, included_sections_json, summary_json,
                warnings_json, files_json
            )
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                request.project_id,
                request.report_title,
                json.dumps(payload["included_sections"]),
                json.dumps(payload["executive_summary"]),
                json.dumps(payload["warnings"]),
                json.dumps(files),
            ),
        )
        report_id = int(cursor.lastrowid)
    return report_id


def create_final_project_report(request: FinalProjectReportRequest) -> FinalProjectReportResponse:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    created = _now()
    created_at = created.isoformat()
    stamp = _timestamp(created)
    payload = _build_payload(request, created_at)
    base = f"final_project_report_{request.project_id or 'global'}_{stamp}"
    files: dict[str, str] = {}
    requested_formats = set(request.formats or ["json"])
    if "json" in requested_formats:
        name = f"{base}.json"
        (REPORT_DIR / name).write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")
        files["json"] = name
    if "pdf" in requested_formats:
        name = f"{base}.pdf"
        (REPORT_DIR / name).write_bytes(_build_pdf(payload))
        files["pdf"] = name
    if "docx" in requested_formats:
        name = f"{base}.docx"
        (REPORT_DIR / name).write_bytes(_build_docx(payload))
        files["docx"] = name
    report_id = _save_report(request, payload, files)
    if request.project_id:
        try:
            attach_project_item(
                request.project_id,
                ProjectAttachRequest(
                    item_type="final_project_report",
                    item_id=str(report_id),
                    item_title=request.report_title,
                    metadata={
                        "workflow_type": "final_end_to_end_report",
                        "report_id": report_id,
                        "included_sections": payload["included_sections"],
                        "missing_sections": payload["missing_sections"],
                        "scientific_notice": SCIENTIFIC_NOTICE,
                    },
                ),
            )
        except Exception:
            pass
    return FinalProjectReportResponse(
        report_id=report_id,
        report_title=request.report_title,
        project_id=request.project_id,
        generated_files={fmt: f"/api/final-report/reports/{report_id}/{fmt}" for fmt in files},
        included_sections=payload["included_sections"],
        missing_sections=payload["missing_sections"],
        warnings=payload["warnings"],
        scientific_notice=SCIENTIFIC_NOTICE,
        created_at=created_at,
    )


def _report_row(report_id: int) -> Any:
    init_db()
    with get_connection() as connection:
        row = connection.execute("SELECT * FROM final_project_reports WHERE id = ?", (report_id,)).fetchone()
    if not row:
        raise HTTPException(status_code=404, detail="Final project report not found.")
    return row


def get_final_project_report(report_id: int) -> FinalProjectReportResponse:
    row = _report_row(report_id)
    files = _json_loads(row["files_json"], {})
    included = _json_loads(row["included_sections_json"], [])
    summary = _json_loads(row["summary_json"], {})
    warnings = _json_loads(row["warnings_json"], [])
    return FinalProjectReportResponse(
        report_id=row["id"],
        report_title=row["report_title"],
        project_id=row["project_id"],
        generated_files={fmt: f"/api/final-report/reports/{row['id']}/{fmt}" for fmt in files},
        included_sections=included,
        missing_sections=summary.get("main_findings", []),
        warnings=warnings,
        scientific_notice=SCIENTIFIC_NOTICE,
        created_at=row["created_at"],
    )


def list_final_project_reports() -> list[dict[str, Any]]:
    init_db()
    with get_connection() as connection:
        rows = connection.execute("SELECT * FROM final_project_reports ORDER BY datetime(created_at) DESC, id DESC LIMIT 50").fetchall()
    return [
        {
            "report_id": row["id"],
            "project_id": row["project_id"],
            "report_title": row["report_title"],
            "included_sections": _json_loads(row["included_sections_json"], []),
            "warnings": _json_loads(row["warnings_json"], []),
            "generated_files": {fmt: f"/api/final-report/reports/{row['id']}/{fmt}" for fmt in _json_loads(row["files_json"], {})},
            "created_at": row["created_at"],
        }
        for row in rows
    ]


def final_report_file_path(report_id: int, file_format: str) -> Path:
    if file_format not in {"json", "pdf", "docx"}:
        raise HTTPException(status_code=404, detail="Unsupported final report format.")
    row = _report_row(report_id)
    files = _json_loads(row["files_json"], {})
    filename = files.get(file_format)
    if not filename:
        raise HTTPException(status_code=404, detail="Final report format was not generated.")
    path = REPORT_DIR / filename
    if not path.exists():
        raise HTTPException(status_code=404, detail="Final report file is missing.")
    return path
