import json
import platform
import sys
from datetime import datetime, timezone
from io import BytesIO
from pathlib import Path
from typing import Any

from docx import Document
from fastapi import HTTPException
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.database import get_connection, init_db
from app.models.final_report_models import (
    FinalProjectReportRequest,
    FinalProjectReportResponse,
    FinalProjectReportSection,
    FinalProjectReportSummary,
)
from app.models.project_workspace_models import ProjectAttachRequest
from app.services.admet_trained_model_service import get_active_trained_model_info
from app.services.local_admet_model import validate_local_admet_model
from app.services.model_registry import model_status_response
from app.services.project_workspace_service import attach_project_item, project_dashboard
from app.services.version import app_version

REPORT_DIR = Path(__file__).resolve().parents[2] / "final_project_reports"
SCIENTIFIC_NOTICE = "Computational decision-support report only. Experimental and clinical interpretation requires qualified scientific review."
FINAL_LIMITATIONS = [
    "This report summarizes stored DrugScreen360 records only; missing data is not inferred.",
    "No experimental result is invented, simulated, or generated by DrugScreen360.",
    "Computational outputs do not prove safety, efficacy, clinical success, regulatory approval, or market readiness.",
    "Applicability-domain, uncertainty, explainability, and model metrics are dataset-dependent.",
    "Qualified scientific review and experimental validation are required before any research decision.",
]


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _timestamp(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%d_%H-%M-%S")


def _safe(value: Any) -> str:
    if value in (None, "", [], {}):
        return "not available"
    if isinstance(value, (dict, list)):
        return json.dumps(value, default=str)[:900]
    return str(value)


def _rows(table: str, project_id: int | None = None, limit: int = 100) -> list[dict[str, Any]]:
    init_db()
    with get_connection() as connection:
        if project_id and table in {
            "experimental_validation_plans",
            "experimental_result_batches",
            "prediction_feedback_summaries",
            "admet_lead_prioritization_runs",
        }:
            rows = connection.execute(
                f"SELECT * FROM {table} WHERE project_id = ? ORDER BY datetime(created_at) DESC, id DESC LIMIT ?",
                (project_id, limit),
            ).fetchall()
        else:
            rows = connection.execute(
                f"SELECT * FROM {table} ORDER BY datetime(created_at) DESC, id DESC LIMIT ?",
                (limit,),
            ).fetchall()
    return [dict(row) for row in rows]


def _json_loads(value: Any, default: Any) -> Any:
    if not value:
        return default
    try:
        return json.loads(value)
    except Exception:
        return default


def _section(section_id: str, title: str, requested: bool, records: list[dict[str, Any]], summary: dict[str, Any], warnings: list[str] | None = None) -> FinalProjectReportSection:
    section_warnings = list(warnings or [])
    included = bool(requested and (records or summary))
    if requested and not included:
        section_warnings.append(f"{title} was requested but no stored records were available.")
    return FinalProjectReportSection(
        section_id=section_id,
        title=title,
        included=included,
        summary=summary if requested else {"status": "not requested"},
        records=records if requested else [],
        warnings=section_warnings,
    )


def _screening_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    records = _rows("screening_history", limit=50)
    summary = {
        "screening_run_count": len(records),
        "recent_compounds": [row.get("compound_name") or row.get("input_query") for row in records[:8]],
        "decisions": {},
    }
    for row in records:
        decision = row.get("decision") or "not available"
        summary["decisions"][decision] = summary["decisions"].get(decision, 0) + 1
    return _section("screening", "Molecule Screening Summary", payload.include_screening, records, summary)


def _training_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    datasets = _rows("admet_datasets", limit=50)
    runs = _rows("admet_training_runs", limit=50)
    summary = {
        "dataset_count": len(datasets),
        "training_run_count": len(runs),
        "latest_training_runs": [
            {
                "id": row.get("id"),
                "task_type": row.get("task_type"),
                "model_type": row.get("model_type"),
                "status": row.get("status"),
                "metrics": _json_loads(row.get("metric_summary_json"), {}),
            }
            for row in runs[:5]
        ],
    }
    return _section("model_training", "ADMET Dataset & Training Summary", payload.include_model_training, datasets + runs, summary)


def _prediction_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    model_status = model_status_response()
    active = get_active_trained_model_info()
    logs = _rows("model_prediction_logs", limit=50)
    summary = {
        "active_trained_model": active,
        "available_models": [item.model_dump() for item in model_status["available_models"]],
        "unavailable_models": [item.model_dump() for item in model_status["unavailable_models"]],
        "prediction_log_count": len(logs),
    }
    return _section("admet_prediction", "Trained Model Prediction Summary", payload.include_admet_prediction, logs, summary)


def _external_validation_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    records = _rows("admet_external_validation_runs", limit=50)
    summary = {
        "external_validation_run_count": len(records),
        "latest_status": records[0].get("status") if records else "not available",
        "latest_metrics": _json_loads(records[0].get("metric_summary_json"), {}) if records else {},
    }
    return _section("external_validation", "External Validation & Calibration", payload.include_external_validation, records, summary)


def _domain_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    records = _rows("admet_domain_evaluations", limit=100)
    counts: dict[str, int] = {}
    uncertainty: dict[str, int] = {}
    for row in records:
        counts[row.get("domain_status") or "unknown"] = counts.get(row.get("domain_status") or "unknown", 0) + 1
        uncertainty[row.get("uncertainty_level") or "unknown"] = uncertainty.get(row.get("uncertainty_level") or "unknown", 0) + 1
    summary = {"domain_status_counts": counts, "uncertainty_distribution": uncertainty, "evaluation_count": len(records)}
    return _section("applicability_domain", "Applicability Domain & Uncertainty", payload.include_applicability_domain, records, summary)


def _explainability_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    records = _rows("admet_prediction_explanations", limit=50)
    evidence: dict[str, int] = {}
    for row in records:
        evidence[row.get("evidence_strength") or "unknown"] = evidence.get(row.get("evidence_strength") or "unknown", 0) + 1
    summary = {
        "explanation_count": len(records),
        "evidence_strength_distribution": evidence,
        "causality_notice": "Feature importance and coefficients are model diagnostics, not biological causality.",
    }
    return _section("explainability", "Prediction Explainability", payload.include_explainability, records, summary)


def _lead_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    records = _rows("admet_lead_prioritization_runs", payload.project_id, limit=50)
    top_candidates = []
    for row in records[:5]:
        summary_json = _json_loads(row.get("summary_json"), {})
        top_candidates.extend((summary_json.get("ranked_candidates") or [])[:3])
    summary = {
        "lead_run_count": len(records),
        "top_candidates": top_candidates[:10],
        "priority_label_counts": {},
    }
    for candidate in top_candidates:
        label = candidate.get("priority_label") or "not available"
        summary["priority_label_counts"][label] = summary["priority_label_counts"].get(label, 0) + 1
    return _section("lead_prioritization", "Lead Prioritization", payload.include_lead_prioritization, records, summary)


def _validation_planner_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    records = _rows("experimental_validation_plans", payload.project_id, limit=50)
    essential = recommended = optional = 0
    for row in records:
        summary_json = _json_loads(row.get("summary_json"), {})
        for candidate in summary_json.get("candidate_plans", []):
            for assay in candidate.get("recommended_assays", []):
                if assay.get("recommendation_priority") == "essential":
                    essential += 1
                elif assay.get("recommendation_priority") == "recommended":
                    recommended += 1
                elif assay.get("recommendation_priority") == "optional":
                    optional += 1
    summary = {
        "validation_plan_count": len(records),
        "essential_assay_count": essential,
        "recommended_assay_count": recommended,
        "optional_assay_count": optional,
        "planning_notice": "Recommended assays are planning support only and are not experimental results.",
    }
    return _section("validation_planner", "Experimental Validation Planner", payload.include_validation_planner, records, summary)


def _experimental_feedback_section(payload: FinalProjectReportRequest) -> FinalProjectReportSection:
    batches = _rows("experimental_result_batches", payload.project_id, limit=50)
    feedback = _rows("prediction_feedback_summaries", payload.project_id, limit=50)
    supported = contradicted = inconclusive = not_comparable = 0
    for row in feedback:
        agreement = _json_loads(row.get("agreement_summary_json"), {})
        supported += int(agreement.get("supported_count") or 0)
        contradicted += int(agreement.get("contradicted_count") or 0)
        inconclusive += int(agreement.get("inconclusive_count") or 0)
        not_comparable += int(agreement.get("not_comparable_count") or 0)
    summary = {
        "result_batch_count": len(batches),
        "feedback_summary_count": len(feedback),
        "supported_count": supported,
        "contradicted_count": contradicted,
        "inconclusive_count": inconclusive,
        "not_comparable_count": not_comparable,
        "no_fake_results_statement": "No experimental results are generated by this report.",
    }
    return _section("experimental_feedback", "Experimental Results Feedback", payload.include_experimental_feedback, batches + feedback, summary)


def _project_context(project_id: int | None) -> dict[str, Any]:
    if not project_id:
        return {"project": None, "dashboard": None, "warnings": ["No project was selected; report summarizes available stored records."]}
    dashboard = project_dashboard(project_id).model_dump()
    return {"project": dashboard.get("project"), "dashboard": dashboard, "warnings": dashboard.get("warnings", [])}


def _build_payload(request: FinalProjectReportRequest, created_at: str) -> dict[str, Any]:
    context = _project_context(request.project_id)
    sections = [
        _screening_section(request),
        _training_section(request),
        _prediction_section(request),
        _external_validation_section(request),
        _domain_section(request),
        _explainability_section(request),
        _lead_section(request),
        _validation_planner_section(request),
        _experimental_feedback_section(request),
    ]
    included = [section.section_id for section in sections if section.included]
    missing = [section.section_id for section in sections if not section.included and section.summary.get("status") != "not requested"]
    warnings = list(context.get("warnings") or [])
    project_items = ((context.get("project") or {}).get("items") or []) if isinstance(context.get("project"), dict) else []
    if any((item.get("metadata") or {}).get("demo_mode") or (item.get("metadata") or {}).get("data_source") == "demo" or "demo" in str(item.get("item_type", "")) for item in project_items):
        warnings.append("Demo data for software demonstration only. Not experimental or clinical evidence.")
    for section in sections:
        warnings.extend(section.warnings)
    screening_count = next((section.summary.get("screening_run_count", 0) for section in sections if section.section_id == "screening"), 0)
    lead_top = next((section.summary.get("top_candidates", []) for section in sections if section.section_id == "lead_prioritization"), [])
    dashboard = context.get("dashboard") or {}
    next_steps = list(dashboard.get("recommended_next_steps") or [])
    if not next_steps:
        next_steps = [
            "Complete missing data before relying on computational summaries.",
            "Run or review experimental validation assays for candidates kept under consideration.",
            "Use model retraining only when enough curated and validated experimental data exists.",
        ]
    summary = FinalProjectReportSummary(
        project_name=(context.get("project") or {}).get("title") if context.get("project") else None,
        generated_at=created_at,
        molecule_or_candidate_count=int(screening_count or len(dashboard.get("candidate_matrix") or [])),
        top_candidates=lead_top[:5],
        main_findings=[
            f"Included sections: {', '.join(included) or 'none'}",
            f"Missing sections: {', '.join(missing) or 'none'}",
        ],
        main_warnings=list(dict.fromkeys(warnings))[:20],
        next_recommended_steps=next_steps,
    )
    return {
        "report_title": request.report_title,
        "project_id": request.project_id,
        "created_at": created_at,
        "app_version": app_version(),
        "scientific_notice": SCIENTIFIC_NOTICE,
        "executive_summary": summary.model_dump(),
        "project_context": context,
        "sections": [section.model_dump() for section in sections],
        "included_sections": included,
        "missing_sections": missing,
        "final_limitations": FINAL_LIMITATIONS,
        "reproducibility": {
            "app_version": app_version(),
            "python_version": sys.version.split()[0],
            "python_implementation": platform.python_implementation(),
            "run_command": ".\\scripts\\start_all.ps1",
            "test_command": ".\\scripts\\run_tests.ps1",
            "generated_at": created_at,
        },
        "warnings": list(dict.fromkeys(warnings)),
    }


def _pdf_table(rows: list[list[str]], widths: list[float] | None = None) -> Table:
    table = Table(rows, colWidths=widths or [2.0 * inch, 4.6 * inch], repeatRows=1 if len(rows) > 1 else 0)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef2f5")),
                ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#c8d1dc")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("FONTSIZE", (0, 0), (-1, -1), 7.2),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    return table


def _pairs(mapping: dict[str, Any]) -> list[list[str]]:
    return [["Field", "Value"], *[[key.replace("_", " ").title(), _safe(value)] for key, value in mapping.items()]]


def _build_pdf(payload: dict[str, Any]) -> bytes:
    buffer = BytesIO()
    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=0.45 * inch, leftMargin=0.45 * inch)
    story = [Paragraph(payload["report_title"], styles["Title"]), Paragraph(payload["scientific_notice"], styles["BodyText"]), Spacer(1, 10)]
    story.append(Paragraph("Executive Summary", styles["Heading2"]))
    story.append(_pdf_table(_pairs(payload["executive_summary"])))
    for section in payload["sections"]:
        story.append(Paragraph(section["title"], styles["Heading2"]))
        if section["included"]:
            story.append(_pdf_table(_pairs(section.get("summary") or {})))
            story.append(Paragraph(f"Stored records summarized: {len(section.get('records') or [])}", styles["BodyText"]))
        else:
            story.append(Paragraph("No stored data available for this section, or the section was not requested.", styles["BodyText"]))
        for warning in section.get("warnings") or []:
            story.append(Paragraph(f"- {warning}", styles["BodyText"]))
    story.append(Paragraph("Final Limitations", styles["Heading2"]))
    for item in payload["final_limitations"]:
        story.append(Paragraph(f"- {item}", styles["BodyText"]))
    story.append(Paragraph("Recommended Next Steps", styles["Heading2"]))
    for item in payload["executive_summary"].get("next_recommended_steps") or []:
        story.append(Paragraph(f"- {item}", styles["BodyText"]))
    story.append(Paragraph("Reproducibility", styles["Heading2"]))
    story.append(_pdf_table(_pairs(payload["reproducibility"])))
    doc.build(story)
    return buffer.getvalue()


def _build_docx(payload: dict[str, Any]) -> bytes:
    document = Document()
    document.add_heading(payload["report_title"], 0)
    document.add_paragraph(payload["scientific_notice"])
    document.add_heading("Executive Summary", level=1)
    for key, value in payload["executive_summary"].items():
        document.add_paragraph(f"{key.replace('_', ' ').title()}: {_safe(value)}")
    for section in payload["sections"]:
        document.add_heading(section["title"], level=1)
        if section["included"]:
            for key, value in (section.get("summary") or {}).items():
                document.add_paragraph(f"{key.replace('_', ' ').title()}: {_safe(value)}")
            document.add_paragraph(f"Stored records summarized: {len(section.get('records') or [])}")
        else:
            document.add_paragraph("No stored data available for this section, or the section was not requested.")
        for warning in section.get("warnings") or []:
            document.add_paragraph(warning, style="List Bullet")
    document.add_heading("Final Limitations", level=1)
    for item in payload["final_limitations"]:
        document.add_paragraph(item, style="List Bullet")
    document.add_heading("Recommended Next Steps", level=1)
    for item in payload["executive_summary"].get("next_recommended_steps") or []:
        document.add_paragraph(item, style="List Bullet")
    document.add_heading("Reproducibility", level=1)
    for key, value in payload["reproducibility"].items():
        document.add_paragraph(f"{key.replace('_', ' ').title()}: {_safe(value)}")
    buffer = BytesIO()
    document.save(buffer)
    return buffer.getvalue()


def _save_report(request: FinalProjectReportRequest, payload: dict[str, Any], files: dict[str, str]) -> int:
    init_db()
    with get_connection() as connection:
        cursor = connection.execute(
            """
            INSERT INTO final_project_reports (
                project_id, report_title, included_sections_json, summary_json,
                warnings_json, files_json
            )
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                request.project_id,
                request.report_title,
                json.dumps(payload["included_sections"]),
                json.dumps(payload["executive_summary"]),
                json.dumps(payload["warnings"]),
                json.dumps(files),
            ),
        )
        report_id = int(cursor.lastrowid)
    return report_id


def create_final_project_report(request: FinalProjectReportRequest) -> FinalProjectReportResponse:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    created = _now()
    created_at = created.isoformat()
    stamp = _timestamp(created)
    payload = _build_payload(request, created_at)
    base = f"final_project_report_{request.project_id or 'global'}_{stamp}"
    files: dict[str, str] = {}
    requested_formats = set(request.formats or ["json"])
    if "json" in requested_formats:
        name = f"{base}.json"
        (REPORT_DIR / name).write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")
        files["json"] = name
    if "pdf" in requested_formats:
        name = f"{base}.pdf"
        (REPORT_DIR / name).write_bytes(_build_pdf(payload))
        files["pdf"] = name
    if "docx" in requested_formats:
        name = f"{base}.docx"
        (REPORT_DIR / name).write_bytes(_build_docx(payload))
        files["docx"] = name
    report_id = _save_report(request, payload, files)
    if request.project_id:
        try:
            attach_project_item(
                request.project_id,
                ProjectAttachRequest(
                    item_type="final_project_report",
                    item_id=str(report_id),
                    item_title=request.report_title,
                    metadata={
                        "workflow_type": "final_end_to_end_report",
                        "report_id": report_id,
                        "included_sections": payload["included_sections"],
                        "missing_sections": payload["missing_sections"],
                        "scientific_notice": SCIENTIFIC_NOTICE,
                    },
                ),
            )
        except Exception:
            pass
    return FinalProjectReportResponse(
        report_id=report_id,
        report_title=request.report_title,
        project_id=request.project_id,
        generated_files={fmt: f"/api/final-report/reports/{report_id}/{fmt}" for fmt in files},
        included_sections=payload["included_sections"],
        missing_sections=payload["missing_sections"],
        warnings=payload["warnings"],
        scientific_notice=SCIENTIFIC_NOTICE,
        created_at=created_at,
    )


def _report_row(report_id: int) -> Any:
    init_db()
    with get_connection() as connection:
        row = connection.execute("SELECT * FROM final_project_reports WHERE id = ?", (report_id,)).fetchone()
    if not row:
        raise HTTPException(status_code=404, detail="Final project report not found.")
    return row


def get_final_project_report(report_id: int) -> FinalProjectReportResponse:
    row = _report_row(report_id)
    files = _json_loads(row["files_json"], {})
    included = _json_loads(row["included_sections_json"], [])
    summary = _json_loads(row["summary_json"], {})
    warnings = _json_loads(row["warnings_json"], [])
    return FinalProjectReportResponse(
        report_id=row["id"],
        report_title=row["report_title"],
        project_id=row["project_id"],
        generated_files={fmt: f"/api/final-report/reports/{row['id']}/{fmt}" for fmt in files},
        included_sections=included,
        missing_sections=summary.get("main_findings", []),
        warnings=warnings,
        scientific_notice=SCIENTIFIC_NOTICE,
        created_at=row["created_at"],
    )


def list_final_project_reports() -> list[dict[str, Any]]:
    init_db()
    with get_connection() as connection:
        rows = connection.execute("SELECT * FROM final_project_reports ORDER BY datetime(created_at) DESC, id DESC LIMIT 50").fetchall()
    return [
        {
            "report_id": row["id"],
            "project_id": row["project_id"],
            "report_title": row["report_title"],
            "included_sections": _json_loads(row["included_sections_json"], []),
            "warnings": _json_loads(row["warnings_json"], []),
            "generated_files": {fmt: f"/api/final-report/reports/{row['id']}/{fmt}" for fmt in _json_loads(row["files_json"], {})},
            "created_at": row["created_at"],
        }
        for row in rows
    ]


def final_report_file_path(report_id: int, file_format: str) -> Path:
    if file_format not in {"json", "pdf", "docx"}:
        raise HTTPException(status_code=404, detail="Unsupported final report format.")
    row = _report_row(report_id)
    files = _json_loads(row["files_json"], {})
    filename = files.get(file_format)
    if not filename:
        raise HTTPException(status_code=404, detail="Final report format was not generated.")
    path = REPORT_DIR / filename
    if not path.exists():
        raise HTTPException(status_code=404, detail="Final report file is missing.")
    return path
